-- PostgreSQL: INSERT
--
-- 参考资料:
--   [1] PostgreSQL Documentation - INSERT
--       https://www.postgresql.org/docs/current/sql-insert.html
--   [2] PostgreSQL Documentation - COPY
--       https://www.postgresql.org/docs/current/sql-copy.html
--   [3] PostgreSQL Source - ExecInsert / heapam.c
--       https://github.com/postgres/postgres/blob/master/src/backend/executor/nodeModifyTable.c

-- ============================================================
-- 1. 基本 INSERT 语法
-- ============================================================

-- 单行插入
INSERT INTO users (username, email, age) VALUES ('alice', 'alice@example.com', 25);

-- 多行插入（单次网络 round-trip，单次 WAL 刷写）
INSERT INTO users (username, email, age) VALUES
    ('alice', 'alice@example.com', 25),
    ('bob', 'bob@example.com', 30),
    ('charlie', 'charlie@example.com', 35);

-- INSERT ... SELECT
INSERT INTO users_archive (username, email, age)
SELECT username, email, age FROM users WHERE age > 60;

-- DEFAULT VALUES（所有列使用默认值）
INSERT INTO logs DEFAULT VALUES RETURNING id;

-- ============================================================
-- 2. RETURNING: INSERT 的返回值
-- ============================================================

INSERT INTO users (username, email, age)
VALUES ('alice', 'alice@example.com', 25)
RETURNING id, username;               -- 返回自增 ID

INSERT INTO users (username, email, age)
VALUES ('alice', 'alice@example.com', 25)
RETURNING *;                          -- 返回完整行（含默认值和生成列）

-- CTE + INSERT + RETURNING
WITH new_user AS (
    INSERT INTO users (username, email)
    VALUES ('alice', 'alice@example.com')
    RETURNING id, username
)
INSERT INTO user_profiles (user_id, display_name)
SELECT id, username FROM new_user;

-- 设计分析:
--   RETURNING 在 INSERT 中特别有价值——获取自增 ID 无需额外 SELECT。
--   MySQL 的 LAST_INSERT_ID() 是会话级全局变量，多行插入只返回第一个 ID。
--   PostgreSQL 的 RETURNING 精确返回每一行的值，语义更清晰。

-- ============================================================
-- 3. OVERRIDING: 覆盖 IDENTITY 列
-- ============================================================

-- GENERATED ALWAYS 列默认禁止手动指定值
-- 需要 OVERRIDING SYSTEM VALUE 显式声明意图
INSERT INTO users (id, username, email)
OVERRIDING SYSTEM VALUE
VALUES (100, 'alice', 'alice@example.com');

-- GENERATED BY DEFAULT 列可以直接指定（无需 OVERRIDING）
-- 设计哲学: ALWAYS 模式通过语法强制保护数据完整性

-- ============================================================
-- 4. COPY: 批量加载的真正利器
-- ============================================================

-- COPY 是 PostgreSQL 的高性能批量加载命令，远快于 INSERT
-- 服务端 COPY（文件在 PostgreSQL 服务器上）
COPY users (username, email, age) FROM '/tmp/users.csv' WITH (FORMAT csv, HEADER);

-- 客户端 \copy（文件在客户端，通过 psql）
-- \copy users FROM '/local/path/users.csv' WITH (FORMAT csv, HEADER);

-- COPY 到标准输出（导出）
COPY users TO '/tmp/users_export.csv' WITH (FORMAT csv, HEADER);

-- COPY FROM STDIN（程序化导入，驱动层常用）
-- libpq: PQputCopyData() + PQputCopyEnd()

-- 性能对比:
--   INSERT:   每行需要解析 SQL、执行计划、WAL、约束检查
--   COPY:     二进制流协议，跳过 SQL 解析，批量 WAL，触发器仍然执行
--   典型场景: 100 万行，INSERT 需要 30s，COPY 只需 3s（10x 差异）
--
-- COPY 的内部优化:
--   (a) 使用专用的 COPY protocol（不经过标准查询处理器）
--   (b) 批量分配 heap pages，减少 buffer 管理开销
--   (c) 批量 WAL 刷写（不是每行一次）
--   (d) 跳过 planner/optimizer 开销

-- ============================================================
-- 5. INSERT 的 MVCC 和 WAL 行为
-- ============================================================

-- 每次 INSERT:
--   (1) 在 heap 中分配空间（可能触发 FSM 查找空闲页）
--   (2) 写入 tuple（设置 xmin = 当前事务 ID）
--   (3) 更新所有索引（每个索引一次写入）
--   (4) 生成 WAL 记录（heap insert + 每个索引 insert）
--
-- 性能瓶颈分析:
--   WAL 是最大瓶颈——每个 INSERT 都要确保 WAL 持久化（fsync/fdatasync）
--   synchronous_commit = off 可以关闭同步 WAL（牺牲持久性换吞吐量）
--   多索引表的 INSERT 更慢——N 个索引 = N 倍索引写入
--
-- UNLOGGED 表: 不写 WAL（崩溃后数据丢失，但写入性能提升 2-5x）
INSERT INTO staging_data (id, data) VALUES (1, '{"key": "value"}');

-- ============================================================
-- 6. 横向对比: INSERT 特性差异
-- ============================================================

-- 1. RETURNING:
--   PostgreSQL: INSERT ... RETURNING *（返回任意表达式）
--   SQL Server: INSERT ... OUTPUT inserted.*
--   MySQL:      不支持（LAST_INSERT_ID() 只返回自增值）
--   Oracle:     INSERT ... RETURNING ... INTO variable（仅 PL/SQL）
--
-- 2. 批量加载:
--   PostgreSQL: COPY（最快），多行 INSERT VALUES
--   MySQL:      LOAD DATA INFILE（类似 COPY），多行 INSERT VALUES
--   Oracle:     SQL*Loader（外部工具），INSERT ALL
--   SQL Server: BULK INSERT, BCP
--   ClickHouse: 直接 INSERT 就是批量模式（面向列存优化）
--
-- 3. INSERT ... SELECT 的隔离性:
--   PostgreSQL: 同一语句中 INSERT 的行对 SELECT 不可见（快照隔离）
--   MySQL:      同上（InnoDB MVCC）
--   这避免了"INSERT INTO t SELECT * FROM t"导致的无限循环

-- ============================================================
-- 7. 对引擎开发者的启示
-- ============================================================

-- (1) COPY 协议是批量写入性能的关键:
--     专用的二进制流协议比逐行 INSERT 快 10x+。
--     新引擎应该从第一天就设计批量写入接口。
--
-- (2) RETURNING 减少 round-trip:
--     应用层常见模式: INSERT 后立即需要自增 ID。
--     没有 RETURNING，需要额外的 SELECT 或依赖不可靠的 LAST_INSERT_ID。
--
-- (3) WAL 是写入瓶颈:
--     PostgreSQL 的 group commit 将多个事务的 WAL 合并刷写。
--     wal_writer_delay 控制刷写频率。
--     设计新引擎时，WAL 批量化是性能的核心优化点。

-- ============================================================
-- 8. 版本演进
-- ============================================================
-- PostgreSQL 8.2:  INSERT ... RETURNING
-- PostgreSQL 8.4:  CTE with INSERT
-- PostgreSQL 9.1:  可写 CTE（WITH ... INSERT ... RETURNING 链式操作）
-- PostgreSQL 9.5:  INSERT ... ON CONFLICT（UPSERT，见 dml/upsert）
-- PostgreSQL 10:   IDENTITY 列（OVERRIDING SYSTEM VALUE）
-- PostgreSQL 12:   COPY FROM 支持 WHERE 过滤
-- PostgreSQL 14:   COPY 性能提升（批量 buffer pin）
-- PostgreSQL 16:   COPY FROM 支持 DEFAULT 关键字
