-- CockroachDB: Sequences & Auto-Increment
--
-- 参考资料:
--   [1] CockroachDB Documentation - CREATE SEQUENCE
--       https://www.cockroachlabs.com/docs/stable/create-sequence
--   [2] CockroachDB Documentation - Serial & unique_rowid()
--       https://www.cockroachlabs.com/docs/stable/serial
--   [3] CockroachDB Documentation - UUID
--       https://www.cockroachlabs.com/docs/stable/uuid

-- ============================================
-- SEQUENCE
-- ============================================
CREATE SEQUENCE user_id_seq;

CREATE SEQUENCE order_id_seq
    START 1
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 10;                              -- 缓存值，减少跨节点协调

-- 使用序列
CREATE TABLE users (
    id       INT DEFAULT nextval('user_id_seq'),
    username VARCHAR(64) NOT NULL
);

-- 获取下一个值
SELECT nextval('user_id_seq');

-- 获取当前值
SELECT currval('user_id_seq');

-- 修改序列
ALTER SEQUENCE user_id_seq RESTART WITH 1000;
ALTER SEQUENCE user_id_seq INCREMENT BY 2;

-- 删除序列
DROP SEQUENCE user_id_seq;
DROP SEQUENCE IF EXISTS user_id_seq;

-- ============================================
-- SERIAL / unique_rowid()
-- CockroachDB 的 SERIAL 默认使用 unique_rowid()（不是真正的自增）
-- ============================================
CREATE TABLE orders (
    id     SERIAL PRIMARY KEY,            -- 等价于 INT DEFAULT unique_rowid()
    amount DECIMAL(10,2)
);
-- unique_rowid() 生成基于时间戳+节点ID的唯一值，分布式安全
-- 值不连续，但全局唯一且大致递增

-- 显式使用 unique_rowid()
CREATE TABLE logs (
    id      INT DEFAULT unique_rowid(),
    message STRING
);

-- ============================================
-- GENERATED AS IDENTITY（v21.1+，兼容 SQL 标准）
-- ============================================
CREATE TABLE accounts (
    id   INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(64)
);

CREATE TABLE products (
    id   INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64)
);

CREATE TABLE items (
    id   INT GENERATED BY DEFAULT AS IDENTITY (START 100 INCREMENT 10),
    name VARCHAR(64)
);

-- ============================================
-- UUID 生成
-- ============================================
CREATE TABLE sessions (
    id         UUID DEFAULT gen_random_uuid(),
    user_id    INT,
    created_at TIMESTAMP DEFAULT current_timestamp()
);

SELECT gen_random_uuid();

-- ============================================
-- 分布式 ID 策略
-- ============================================
-- unique_rowid(): CockroachDB 推荐的默认方案
--   优点：分布式安全，无跨节点协调，不会产生写热点
--   缺点：值不连续，占用空间较大
-- SEQUENCE: 兼容 PostgreSQL，但在分布式环境中有性能损耗
--   CACHE 可以减少协调开销
-- UUID: 适合不需要排序的场景
-- GENERATED AS IDENTITY: SQL 标准兼容，内部也使用序列

-- ============================================
-- 序列 vs 自增 权衡
-- ============================================
-- 1. unique_rowid()（推荐）：分布式安全，性能最佳，但值不连续
-- 2. UUID：适合微服务、跨数据库场景
-- 3. SEQUENCE：值连续但有分布式协调开销（使用 CACHE 缓解）
-- 4. GENERATED AS IDENTITY：SQL 标准兼容
