-- Databricks: Sequences & Auto-Increment
--
-- 参考资料:
--   [1] Databricks SQL Reference - Generated Columns
--       https://docs.databricks.com/sql/language-manual/sql-ref-syntax-ddl-create-table-using.html
--   [2] Databricks Documentation - Identity Columns
--       https://docs.databricks.com/sql/language-manual/sql-ref-syntax-ddl-create-table-identity-column.html
--   [3] Databricks Documentation - Delta Lake
--       https://docs.databricks.com/delta/index.html

-- ============================================
-- Databricks 不支持 CREATE SEQUENCE
-- 以下是替代方案
-- ============================================

-- ============================================
-- IDENTITY 列（Databricks SQL, Unity Catalog）
-- ============================================
CREATE TABLE users (
    id       BIGINT GENERATED ALWAYS AS IDENTITY,
    username STRING NOT NULL,
    email    STRING NOT NULL
);

CREATE TABLE orders (
    id       BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    user_id  BIGINT,
    amount   DECIMAL(10,2)
);

CREATE TABLE products (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name     STRING NOT NULL
);
-- GENERATED BY DEFAULT 允许手动指定 ID

-- ============================================
-- 使用 monotonically_increasing_id()（Spark SQL）
-- ============================================
-- 注意：不保证连续，每个分区独立生成
-- SELECT monotonically_increasing_id() AS id, * FROM source_table;

-- ============================================
-- 使用 ROW_NUMBER() 窗口函数
-- ============================================
SELECT
    ROW_NUMBER() OVER (ORDER BY created_at) AS row_id,
    username,
    email
FROM users;

-- ============================================
-- UUID 生成
-- ============================================
SELECT uuid();
-- 结果示例：'7f1b7e42-3a1c-4b5d-8f2e-9c0d1e2f3a4b'

CREATE TABLE sessions (
    id         STRING DEFAULT uuid(),
    user_id    BIGINT,
    created_at TIMESTAMP DEFAULT current_timestamp()
);

-- ============================================
-- 序列 vs 自增 权衡
-- ============================================
-- 1. IDENTITY 列（推荐）：Delta Lake 原生支持
-- 2. uuid()：适合分布式唯一标识
-- 3. monotonically_increasing_id()：仅适合 Spark DataFrame 操作，不持久化
-- 4. ROW_NUMBER()：查询时生成，不适合持久化

-- 限制：
-- 不支持 CREATE SEQUENCE
-- IDENTITY 列仅支持 Delta Lake 表
-- IDENTITY 值在并发写入时可能不连续
-- GENERATED ALWAYS AS IDENTITY 不允许手动指定值
