-- DB2: Sequences & Auto-Increment
--
-- 参考资料:
--   [1] IBM DB2 Documentation - CREATE SEQUENCE
--       https://www.ibm.com/docs/en/db2/11.5?topic=statements-create-sequence
--   [2] IBM DB2 Documentation - Identity Columns
--       https://www.ibm.com/docs/en/db2/11.5?topic=columns-identity
--   [3] IBM DB2 Documentation - NEXT VALUE expression
--       https://www.ibm.com/docs/en/db2/11.5?topic=expressions-next-value

-- ============================================
-- SEQUENCE
-- ============================================
CREATE SEQUENCE user_id_seq
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    CACHE 20
    ORDER;                                    -- ORDER 保证严格递增（分布式环境）

-- 使用序列
INSERT INTO users (id, username) VALUES (NEXT VALUE FOR user_id_seq, 'alice');
SELECT NEXT VALUE FOR user_id_seq FROM SYSIBM.SYSDUMMY1;
SELECT PREVIOUS VALUE FOR user_id_seq FROM SYSIBM.SYSDUMMY1;

-- 修改序列
ALTER SEQUENCE user_id_seq RESTART WITH 1000;
ALTER SEQUENCE user_id_seq INCREMENT BY 2;
ALTER SEQUENCE user_id_seq CACHE 50;

-- 删除序列
DROP SEQUENCE user_id_seq;

-- ============================================
-- IDENTITY 列
-- ============================================
-- GENERATED ALWAYS（不允许手动指定值）
CREATE TABLE users (
    id       BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY
                    (START WITH 1 INCREMENT BY 1),
    username VARCHAR(64) NOT NULL,
    email    VARCHAR(255) NOT NULL
);

-- GENERATED BY DEFAULT（允许手动指定值）
CREATE TABLE orders (
    id       BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY
                    (START WITH 1 INCREMENT BY 1),
    amount   DECIMAL(10,2)
);

-- 带 CACHE 和 ORDER 的 IDENTITY
CREATE TABLE logs (
    id       BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY
                    (START WITH 1 INCREMENT BY 1 CACHE 100 ORDER),
    message  VARCHAR(1000)
);

-- 获取最后生成的 IDENTITY 值
VALUES IDENTITY_VAL_LOCAL();

-- 覆盖 GENERATED ALWAYS（特殊场景）
INSERT INTO users (id, username, email)
    OVERRIDING SYSTEM VALUE
    VALUES (999, 'admin', 'admin@example.com');

-- ============================================
-- UUID 生成（DB2 11.1+）
-- ============================================
VALUES SYSPROC.GENERATE_UNIQUE();             -- 返回 CHAR(13) FOR BIT DATA
-- 或使用 UDF：
-- VALUES HEX(GENERATE_UNIQUE());

-- ============================================
-- 序列 vs 自增 权衡
-- ============================================
-- 1. IDENTITY：简单，绑定到表，一张表只能有一个
-- 2. SEQUENCE：灵活，可跨表共享，支持 ORDER 保证严格有序
-- 3. GENERATED ALWAYS：数据库完全控制值的生成
-- 4. GENERATED BY DEFAULT：允许手动指定，适合数据迁移
-- 5. GENERATE_UNIQUE()：适合需要唯一标识但不需要连续递增的场景
