-- Derby: Sequences & Auto-Increment
--
-- 参考资料:
--   [1] Apache Derby Documentation - IDENTITY Columns
--       https://db.apache.org/derby/docs/10.16/ref/rrefsqlj37836.html
--   [2] Apache Derby Documentation - CREATE SEQUENCE
--       https://db.apache.org/derby/docs/10.16/ref/rrefsqljcreatesequence.html
--   [3] Apache Derby Documentation - NEXT VALUE FOR
--       https://db.apache.org/derby/docs/10.16/ref/rrefsqljnextvaluefor.html

-- ============================================
-- IDENTITY 列
-- ============================================
-- GENERATED ALWAYS
CREATE TABLE users (
    id       BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY
                    (START WITH 1, INCREMENT BY 1),
    username VARCHAR(64) NOT NULL,
    email    VARCHAR(255) NOT NULL
);

-- GENERATED BY DEFAULT
CREATE TABLE orders (
    id       BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    amount   DECIMAL(10,2)
);

-- 获取最后生成的 IDENTITY 值
VALUES IDENTITY_VAL_LOCAL();

-- ============================================
-- SEQUENCE（Derby 10.6+）
-- ============================================
CREATE SEQUENCE user_id_seq
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE;

-- 使用序列
INSERT INTO users (id, username) VALUES (NEXT VALUE FOR user_id_seq, 'alice');
SELECT NEXT VALUE FOR user_id_seq FROM SYSIBM.SYSDUMMY1;

-- 删除序列
DROP SEQUENCE user_id_seq RESTRICT;

-- ============================================
-- UUID 生成
-- Derby 没有内置 UUID 函数，需要通过 Java 函数实现
-- ============================================
-- CREATE FUNCTION uuid()
--     RETURNS VARCHAR(36)
--     LANGUAGE JAVA
--     PARAMETER STYLE JAVA
--     NO SQL
--     EXTERNAL NAME 'java.util.UUID.randomUUID().toString';

-- ============================================
-- 序列 vs 自增 权衡
-- ============================================
-- 1. IDENTITY：简单，嵌入式应用首选
-- 2. SEQUENCE：灵活，可跨表共享
-- 3. Derby 作为嵌入式数据库，通常不需要分布式 ID 策略
-- 4. GENERATED ALWAYS 更安全，防止手动指定导致冲突
