-- Firebird: Sequences & Auto-Increment
--
-- 参考资料:
--   [1] Firebird Documentation - CREATE SEQUENCE / GENERATOR
--       https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-ddl-sequence
--   [2] Firebird Documentation - IDENTITY Columns
--       https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-ddl-tbl-identity
--   [3] Firebird Documentation - GEN_UUID()
--       https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-funcs-gen-uuid

-- ============================================
-- SEQUENCE (也称为 GENERATOR)
-- Firebird 的 SEQUENCE 和 GENERATOR 是同义词
-- ============================================
CREATE SEQUENCE user_id_seq;
-- 或旧语法：CREATE GENERATOR user_id_seq;

CREATE SEQUENCE order_id_seq START WITH 1000 INCREMENT BY 1;

-- 获取下一个值
SELECT NEXT VALUE FOR user_id_seq FROM RDB$DATABASE;
-- 旧语法：SELECT GEN_ID(user_id_seq, 1) FROM RDB$DATABASE;

-- 在插入中使用
INSERT INTO users (id, username) VALUES (NEXT VALUE FOR user_id_seq, 'alice');

-- 修改序列
ALTER SEQUENCE user_id_seq RESTART WITH 1000;
ALTER SEQUENCE user_id_seq INCREMENT BY 2;

-- 删除序列
DROP SEQUENCE user_id_seq;
-- 旧语法：DROP GENERATOR user_id_seq;

-- ============================================
-- IDENTITY 列（Firebird 3.0+）
-- ============================================
-- GENERATED BY DEFAULT
CREATE TABLE users (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(64) NOT NULL,
    email    VARCHAR(255) NOT NULL
);

-- GENERATED ALWAYS（Firebird 4.0+）
CREATE TABLE orders (
    id       INTEGER GENERATED ALWAYS AS IDENTITY,
    amount   DECIMAL(10,2)
);

-- 带参数的 IDENTITY
CREATE TABLE products (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1),
    name     VARCHAR(64)
);

-- ============================================
-- 使用触发器实现自增（Firebird 2.x 及更早版本的传统方式）
-- ============================================
CREATE SEQUENCE users_id_gen;

CREATE TRIGGER trg_users_bi FOR users
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.id IS NULL) THEN
        NEW.id = NEXT VALUE FOR users_id_gen;
END;

-- ============================================
-- UUID 生成
-- ============================================
SELECT GEN_UUID() FROM RDB$DATABASE;          -- 返回 OCTETS（16 字节二进制）
SELECT UUID_TO_CHAR(GEN_UUID()) FROM RDB$DATABASE;  -- Firebird 4.0+，返回 VARCHAR

-- ============================================
-- 序列 vs 自增 权衡
-- ============================================
-- 1. IDENTITY（3.0+）：最简单，推荐新项目使用
-- 2. SEQUENCE + 触发器：传统方式，兼容旧版本
-- 3. SEQUENCE：灵活，可跨表共享
-- 4. GEN_UUID()：全局唯一，适合分布式场景
-- 5. GENERATED ALWAYS（4.0+）比 BY DEFAULT 更安全
