-- H2: Sequences & Auto-Increment
--
-- 参考资料:
--   [1] H2 Documentation - CREATE SEQUENCE
--       https://h2database.com/html/commands.html#create_sequence
--   [2] H2 Documentation - Auto-Increment / Identity
--       https://h2database.com/html/commands.html#create_table
--   [3] H2 Documentation - Data Types
--       https://h2database.com/html/datatypes.html

-- ============================================
-- SEQUENCE
-- ============================================
CREATE SEQUENCE user_id_seq;

CREATE SEQUENCE order_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 32
    NO CYCLE;

-- 使用序列
INSERT INTO users (id, username) VALUES (NEXT VALUE FOR user_id_seq, 'alice');
SELECT NEXT VALUE FOR user_id_seq;
SELECT CURRENT VALUE FOR user_id_seq;

-- 修改序列
ALTER SEQUENCE user_id_seq RESTART WITH 1000;
ALTER SEQUENCE user_id_seq INCREMENT BY 2;

-- 删除序列
DROP SEQUENCE user_id_seq;
DROP SEQUENCE IF EXISTS user_id_seq;

-- ============================================
-- IDENTITY 列
-- ============================================
-- GENERATED ALWAYS AS IDENTITY（推荐，H2 2.0+）
CREATE TABLE users (
    id       BIGINT GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(64) NOT NULL,
    email    VARCHAR(255) NOT NULL
);

-- GENERATED BY DEFAULT AS IDENTITY
CREATE TABLE orders (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    amount   DECIMAL(10,2)
);

-- 传统 AUTO_INCREMENT 语法（H2 兼容模式）
CREATE TABLE legacy_users (
    id       BIGINT AUTO_INCREMENT,
    username VARCHAR(64)
);

-- IDENTITY 类型（H2 特有的简写）
CREATE TABLE items (
    id       IDENTITY,                       -- 等价于 BIGINT GENERATED BY DEFAULT AS IDENTITY
    name     VARCHAR(64)
);

-- ============================================
-- UUID 生成
-- ============================================
SELECT RANDOM_UUID();
-- 或
SELECT UUID();

CREATE TABLE sessions (
    id         UUID DEFAULT RANDOM_UUID(),
    user_id    BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 序列 vs 自增 权衡
-- ============================================
-- 1. GENERATED AS IDENTITY（推荐）：SQL 标准，H2 2.0+
-- 2. IDENTITY 类型：H2 特有简写，方便快捷
-- 3. SEQUENCE：灵活，可跨表共享
-- 4. AUTO_INCREMENT：兼容 MySQL 模式
-- 5. RANDOM_UUID()：全局唯一标识
-- H2 作为测试/嵌入式数据库，建议使用与生产库兼容的语法
