-- KingbaseES (人大金仓): Sequences & Auto-Increment
--
-- 参考资料:
--   [1] KingbaseES SQL 参考手册 - CREATE SEQUENCE
--       https://help.kingbase.com.cn/v8/development/sql/sql/SQL_Statements_7.html
--   [2] KingbaseES SQL 参考手册 - Identity Columns
--       https://help.kingbase.com.cn/v8/development/sql/sql/SQL_Statements_10.html

-- ============================================
-- SEQUENCE（兼容 PostgreSQL）
-- ============================================
CREATE SEQUENCE user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 20;

-- 使用序列
INSERT INTO users (id, username) VALUES (nextval('user_id_seq'), 'alice');
SELECT nextval('user_id_seq');
SELECT currval('user_id_seq');
SELECT setval('user_id_seq', 1000);

-- 修改序列
ALTER SEQUENCE user_id_seq RESTART WITH 1000;

-- 删除序列
DROP SEQUENCE user_id_seq;
DROP SEQUENCE IF EXISTS user_id_seq;

-- ============================================
-- SERIAL / BIGSERIAL
-- ============================================
CREATE TABLE users (
    id       BIGSERIAL PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    email    VARCHAR(255) NOT NULL
);

-- ============================================
-- GENERATED AS IDENTITY
-- ============================================
CREATE TABLE orders (
    id       BIGINT GENERATED ALWAYS AS IDENTITY,
    amount   DECIMAL(10,2)
);

CREATE TABLE products (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1),
    name     VARCHAR(64)
);

-- ============================================
-- Oracle 兼容模式
-- KingbaseES 在 Oracle 兼容模式下支持 Oracle 风格的序列
-- ============================================
-- CREATE SEQUENCE user_id_seq START WITH 1 INCREMENT BY 1;
-- SELECT user_id_seq.NEXTVAL FROM DUAL;
-- SELECT user_id_seq.CURRVAL FROM DUAL;

-- ============================================
-- UUID 生成
-- ============================================
-- 需要 uuid-ossp 扩展
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
SELECT uuid_generate_v4();

SELECT sys_guid();                           -- KingbaseES 兼容 Oracle 的 SYS_GUID

-- ============================================
-- 序列 vs 自增 权衡
-- ============================================
-- 1. SERIAL/BIGSERIAL：简单，兼容 PostgreSQL
-- 2. GENERATED AS IDENTITY：SQL 标准兼容
-- 3. SEQUENCE：灵活，可跨表共享
-- 4. UUID：全局唯一
-- 5. KingbaseES 同时支持 PostgreSQL 和 Oracle 两种语法风格
