-- openGauss: Sequences & Auto-Increment
--
-- 参考资料:
--   [1] openGauss Documentation - CREATE SEQUENCE
--       https://docs.opengauss.org/zh/docs/latest/docs/SQLReference/CREATE-SEQUENCE.html
--   [2] openGauss Documentation - Serial Types
--       https://docs.opengauss.org/zh/docs/latest/docs/SQLReference/CREATE-TABLE.html

-- ============================================
-- SEQUENCE（兼容 PostgreSQL）
-- ============================================
CREATE SEQUENCE user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 20;

-- 使用序列
INSERT INTO users (id, username) VALUES (nextval('user_id_seq'), 'alice');
SELECT nextval('user_id_seq');
SELECT currval('user_id_seq');
SELECT setval('user_id_seq', 1000);

-- 修改序列
ALTER SEQUENCE user_id_seq RESTART WITH 1000;
ALTER SEQUENCE user_id_seq OWNED BY users.id;

-- 删除序列
DROP SEQUENCE user_id_seq;
DROP SEQUENCE IF EXISTS user_id_seq;

-- ============================================
-- SERIAL / BIGSERIAL
-- ============================================
CREATE TABLE users (
    id       BIGSERIAL PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    email    VARCHAR(255) NOT NULL
);

-- SMALLSERIAL / SERIAL / BIGSERIAL
-- 分别对应 SMALLINT / INTEGER / BIGINT

-- ============================================
-- GENERATED AS IDENTITY
-- ============================================
CREATE TABLE orders (
    id       BIGINT GENERATED ALWAYS AS IDENTITY,
    amount   DECIMAL(10,2)
);

CREATE TABLE products (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1),
    name     VARCHAR(64)
);

-- ============================================
-- 大序列（LARGE SEQUENCE，openGauss 特有）
-- 适用于需要更大范围的序列值
-- ============================================
CREATE LARGE SEQUENCE large_id_seq
    START WITH 1
    INCREMENT BY 1;

SELECT nextval('large_id_seq');

-- ============================================
-- UUID 生成
-- ============================================
SELECT sys_guid();                           -- openGauss 内置
-- 需要 uuid-ossp 扩展获取标准格式
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
SELECT uuid_generate_v4();

-- ============================================
-- 序列 vs 自增 权衡
-- ============================================
-- 1. SERIAL/BIGSERIAL：简单，兼容 PostgreSQL
-- 2. GENERATED AS IDENTITY：SQL 标准兼容
-- 3. SEQUENCE：灵活，可跨表共享
-- 4. LARGE SEQUENCE：openGauss 特有，支持更大范围
-- 5. UUID：全局唯一
