-- Oracle: Sequences & Auto-Increment
--
-- 参考资料:
--   [1] Oracle Documentation - CREATE SEQUENCE
--       https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/CREATE-SEQUENCE.html
--   [2] Oracle Documentation - Identity Columns
--       https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/CREATE-TABLE.html
--   [3] Oracle Documentation - SYS_GUID
--       https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/SYS_GUID.html

-- ============================================
-- SEQUENCE
-- ============================================
CREATE SEQUENCE user_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999999999
    CACHE 20
    NO CYCLE
    ORDER;                                   -- ORDER 保证 RAC 环境中严格有序

-- 使用序列
INSERT INTO users (id, username) VALUES (user_id_seq.NEXTVAL, 'alice');
SELECT user_id_seq.NEXTVAL FROM DUAL;
SELECT user_id_seq.CURRVAL FROM DUAL;

-- 序列作为默认值（Oracle 12c+）
CREATE TABLE orders (
    id       NUMBER DEFAULT user_id_seq.NEXTVAL,
    amount   NUMBER(10,2)
);

-- 修改序列
ALTER SEQUENCE user_id_seq INCREMENT BY 2;
ALTER SEQUENCE user_id_seq CACHE 100;
ALTER SEQUENCE user_id_seq RESTART START WITH 1000;  -- 18c+

-- 删除序列
DROP SEQUENCE user_id_seq;

-- ============================================
-- IDENTITY 列（Oracle 12c+）
-- ============================================
-- GENERATED ALWAYS
CREATE TABLE users (
    id       NUMBER GENERATED ALWAYS AS IDENTITY,
    username VARCHAR2(64) NOT NULL,
    email    VARCHAR2(255) NOT NULL
);

-- GENERATED BY DEFAULT
CREATE TABLE orders (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    amount   NUMBER(10,2)
);

-- GENERATED BY DEFAULT ON NULL（Oracle 12c+）
-- 当插入 NULL 时也自动生成值
CREATE TABLE products (
    id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                    (START WITH 100 INCREMENT BY 1),
    name     VARCHAR2(64)
);

-- 带参数的 IDENTITY
CREATE TABLE logs (
    id       NUMBER GENERATED ALWAYS AS IDENTITY
                    (START WITH 1 INCREMENT BY 1 CACHE 100 ORDER),
    message  VARCHAR2(4000)
);

-- ============================================
-- UUID 生成
-- ============================================
SELECT SYS_GUID() FROM DUAL;
-- 返回 32 位十六进制字符串（RAW(16)），如 'A1B2C3D4E5F6A1B2C3D4E5F6A1B2C3D4'

-- 格式化为标准 UUID
SELECT REGEXP_REPLACE(SYS_GUID(),
    '(.{8})(.{4})(.{4})(.{4})(.{12})',
    '\1-\2-\3-\4-\5')
FROM DUAL;

-- ============================================
-- 序列 vs 自增 权衡
-- ============================================
-- 1. SEQUENCE：Oracle 传统方式，灵活，可跨表共享
-- 2. IDENTITY（12c+推荐）：简洁，SQL 标准兼容
-- 3. GENERATED BY DEFAULT ON NULL：最灵活的 IDENTITY 模式
-- 4. SYS_GUID()：全局唯一，RAC 环境安全
-- 5. SEQUENCE + ORDER：RAC 环境中保证严格有序（有性能代价）
-- 6. SEQUENCE + NOORDER + CACHE：性能最佳，但不保证全局有序
