-- Oracle: 序列与自增 (Sequences & Auto-Increment)
--
-- 参考资料:
--   [1] Oracle SQL Language Reference - CREATE SEQUENCE
--       https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/CREATE-SEQUENCE.html
--   [2] Oracle SQL Language Reference - Identity Columns
--       https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/CREATE-TABLE.html

-- ============================================================
-- 1. SEQUENCE（Oracle 传统方式，8i+）
-- ============================================================

CREATE SEQUENCE user_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999999999
    CACHE 20
    NO CYCLE
    ORDER;                                     -- ORDER: RAC 环境严格有序

-- 使用序列（注意: 必须 FROM DUAL）
INSERT INTO users (id, username) VALUES (user_id_seq.NEXTVAL, 'alice');
SELECT user_id_seq.NEXTVAL FROM DUAL;
SELECT user_id_seq.CURRVAL FROM DUAL;          -- 必须先调用过 NEXTVAL

-- 序列作为默认值（12c+）
CREATE TABLE orders (
    id     NUMBER DEFAULT user_id_seq.NEXTVAL,
    amount NUMBER(10,2)
);

-- 修改序列
ALTER SEQUENCE user_id_seq INCREMENT BY 2;
ALTER SEQUENCE user_id_seq CACHE 100;
ALTER SEQUENCE user_id_seq RESTART START WITH 1000;  -- 18c+

-- 删除序列
DROP SEQUENCE user_id_seq;

-- ============================================================
-- 2. IDENTITY 列（12c+，SQL 标准方式）
-- ============================================================

-- GENERATED ALWAYS（不允许手动指定值）
CREATE TABLE users (
    id       NUMBER GENERATED ALWAYS AS IDENTITY,
    username VARCHAR2(64) NOT NULL
);

-- GENERATED BY DEFAULT（允许手动指定值，未指定时自动生成）
CREATE TABLE orders (
    id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    amount NUMBER(10,2)
);

-- GENERATED BY DEFAULT ON NULL（最灵活: 值为 NULL 时也自动生成）
CREATE TABLE products (
    id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                (START WITH 100 INCREMENT BY 1),
    name VARCHAR2(64)
);

-- 带完整参数的 IDENTITY
CREATE TABLE logs (
    id      NUMBER GENERATED ALWAYS AS IDENTITY
                   (START WITH 1 INCREMENT BY 1 CACHE 100 ORDER),
    message VARCHAR2(4000)
);

-- ============================================================
-- 3. 设计决策分析（对 SQL 引擎开发者）
-- ============================================================

-- 3.1 SEQUENCE 独立对象 vs IDENTITY 列绑定
--
-- Oracle 长期坚持 SEQUENCE 独立于表的设计（8i~11g），12c 才加入 IDENTITY。
-- 这反映了两种哲学:
--
-- SEQUENCE（独立对象）:
--   优点: 可跨表共享、可在非 INSERT 场景使用（如编号生成）
--   缺点: 需要单独管理生命周期、容易忘记创建/删除
--
-- IDENTITY（绑定到列）:
--   优点: 简单、自包含、SQL 标准兼容
--   缺点: 不可跨表共享、灵活性低
--
-- 横向对比:
--   Oracle:     SEQUENCE(8i+) + IDENTITY(12c+)，两者并存
--   PostgreSQL: SEQUENCE(一直有) + SERIAL(语法糖) + IDENTITY(10+)
--   MySQL:      AUTO_INCREMENT（仅列绑定，无独立序列）
--   SQL Server: IDENTITY(一直有) + SEQUENCE(2012+)
--   SQLite:     INTEGER PRIMARY KEY 自动成为 rowid（最简单）
--   分布式:     BigQuery/Spanner 无自增（分布式不推荐全局序列）
--
-- 对引擎开发者的启示:
--   推荐同时支持两种: SEQUENCE 满足高级用户，IDENTITY 满足简单场景。
--   分布式引擎中全局序列代价高，可考虑段分配（TiDB）或放弃连续性（Snowflake）。

-- 3.2 CACHE vs ORDER: 性能与有序性的权衡
--
-- CACHE 20: 每次从共享池预取 20 个值到实例本地缓存
--   优点: 减少共享池访问，高并发性能好
--   缺点: 实例崩溃丢失未使用的缓存值（产生间隙）
--
-- ORDER: 保证跨 RAC 实例严格有序
--   代价: 每次 NEXTVAL 都要跨实例协调，性能大幅下降
--   如果不需要跨实例有序: 使用 NOORDER（默认）
--
-- NOCACHE: 每次都从数据字典读取（最慢，但不丢失值）
--
-- 对比:
--   MySQL AUTO_INCREMENT: innodb_autoinc_lock_mode 控制锁粒度
--   PostgreSQL SEQUENCE: 也有 CACHE 选项，语义类似
--
-- 对引擎开发者的启示:
--   序列实现的核心问题是"持久化 vs 性能":
--   方案 A: 每次持久化（NOCACHE，最安全但最慢）
--   方案 B: 批量预取+崩溃丢失（CACHE，Oracle 默认）
--   方案 C: WAL 持久化（MySQL 8.0 做法: 自增值写 redo log）

-- 3.3 GENERATED BY DEFAULT ON NULL: Oracle 的创新
-- 这是 Oracle 12c 独有的 IDENTITY 模式，解决了一个常见问题:
--   INSERT INTO t (id, name) VALUES (NULL, 'test');
-- 在 BY DEFAULT 模式: 插入 NULL（可能违反 NOT NULL）
-- 在 BY DEFAULT ON NULL 模式: NULL 被替换为自动生成值
--
-- 这对 ORM 和应用框架很有用（它们常常显式传 NULL）
-- PostgreSQL 和 SQL Server 不支持这种模式

-- ============================================================
-- 4. UUID 生成
-- ============================================================
SELECT SYS_GUID() FROM DUAL;
-- 返回 RAW(16)，如 'A1B2C3D4E5F6A1B2C3D4E5F6A1B2C3D4'

-- 格式化为标准 UUID
SELECT REGEXP_REPLACE(SYS_GUID(),
    '(.{8})(.{4})(.{4})(.{4})(.{12})',
    '\1-\2-\3-\4-\5')
FROM DUAL;

-- 横向对比:
--   Oracle:     SYS_GUID() -- RAW(16)，基于主机标识+时间，非随机
--   PostgreSQL: gen_random_uuid() (13+) -- UUIDv4 (随机)
--   MySQL:      UUID() -- UUIDv1 (时间+MAC)
--   SQL Server: NEWID() (随机) / NEWSEQUENTIALID() (顺序，减少索引碎片)

-- ============================================================
-- 5. 数据字典查询
-- ============================================================
SELECT sequence_name, min_value, max_value, increment_by,
       cache_size, last_number, order_flag
FROM user_sequences;

-- 查看 IDENTITY 列
SELECT table_name, column_name, generation_type, identity_options
FROM user_tab_identity_cols;

-- ============================================================
-- 6. 总结: 自增策略选择矩阵
-- ============================================================
-- 场景                     推荐方式
-- 单表自增主键（简单）       IDENTITY (12c+)
-- 单表自增主键（灵活控制）   SEQUENCE + DEFAULT
-- 跨表共享序列号            SEQUENCE
-- RAC 环境严格有序           SEQUENCE + ORDER + CACHE
-- 全局唯一标识              SYS_GUID()
-- 分布式环境               UUID（避免全局序列的性能瓶颈）
