-- PostgreSQL: Sequences & Auto-Increment
--
-- 参考资料:
--   [1] PostgreSQL Documentation - CREATE SEQUENCE
--       https://www.postgresql.org/docs/current/sql-createsequence.html
--   [2] PostgreSQL Documentation - Serial Types
--       https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-SERIAL
--   [3] PostgreSQL Documentation - Identity Columns
--       https://www.postgresql.org/docs/current/sql-createtable.html

-- ============================================
-- SEQUENCE
-- ============================================
CREATE SEQUENCE user_id_seq;

CREATE SEQUENCE order_id_seq
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- 使用序列
INSERT INTO users (id, username) VALUES (nextval('user_id_seq'), 'alice');
SELECT nextval('user_id_seq');
SELECT currval('user_id_seq');               -- 当前会话最近的 nextval 值
SELECT lastval();                            -- 当前会话最近任意序列的 nextval 值
SELECT setval('user_id_seq', 1000);          -- 设置当前值
SELECT setval('user_id_seq', 1000, false);   -- 下次 nextval 返回 1000

-- 修改序列
ALTER SEQUENCE user_id_seq RESTART WITH 1000;
ALTER SEQUENCE user_id_seq INCREMENT BY 2;
ALTER SEQUENCE user_id_seq OWNED BY users.id;  -- 关联到列（DROP 表时自动删除）

-- 删除序列
DROP SEQUENCE user_id_seq;
DROP SEQUENCE IF EXISTS user_id_seq;
DROP SEQUENCE user_id_seq CASCADE;

-- ============================================
-- SERIAL / BIGSERIAL（传统方式）
-- ============================================
CREATE TABLE users (
    id       BIGSERIAL PRIMARY KEY,           -- 等价于 CREATE SEQUENCE + DEFAULT nextval
    username VARCHAR(64) NOT NULL,
    email    VARCHAR(255) NOT NULL
);

-- SMALLSERIAL (SMALLINT), SERIAL (INTEGER), BIGSERIAL (BIGINT)

-- ============================================
-- GENERATED AS IDENTITY（PostgreSQL 10+，推荐）
-- ============================================
-- GENERATED ALWAYS（不允许手动指定值）
CREATE TABLE orders (
    id       BIGINT GENERATED ALWAYS AS IDENTITY,
    amount   NUMERIC(10,2)
);

-- GENERATED BY DEFAULT（允许手动指定值）
CREATE TABLE products (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name     VARCHAR(64)
);

-- 带参数的 IDENTITY
CREATE TABLE logs (
    id       BIGINT GENERATED ALWAYS AS IDENTITY
                    (START WITH 1 INCREMENT BY 1 CACHE 100),
    message  TEXT
);

-- 覆盖 GENERATED ALWAYS
INSERT INTO orders (id, amount) OVERRIDING SYSTEM VALUE VALUES (999, 99.99);

-- ============================================
-- UUID 生成
-- ============================================
-- gen_random_uuid()（PostgreSQL 13+ 内置）
SELECT gen_random_uuid();

-- uuid-ossp 扩展（13 之前版本）
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
SELECT uuid_generate_v4();
SELECT uuid_generate_v1();                   -- 时间 + MAC 地址

CREATE TABLE sessions (
    id         UUID DEFAULT gen_random_uuid(),
    user_id    BIGINT,
    created_at TIMESTAMP DEFAULT current_timestamp
);

-- ============================================
-- 序列 vs 自增 权衡
-- ============================================
-- 1. GENERATED AS IDENTITY（10+ 推荐）：SQL 标准，最佳实践
-- 2. SERIAL/BIGSERIAL：传统方式，仍然广泛使用
-- 3. SEQUENCE：灵活，可跨表共享
-- 4. UUID：全局唯一，适合分布式系统
-- 5. IDENTITY 比 SERIAL 更严格（ALWAYS 防止意外覆盖）
-- 6. SERIAL 只是语法糖（CREATE SEQUENCE + DEFAULT）
