-- SQL Standard (ISO/IEC 9075): Sequences & Auto-Increment
--
-- 参考资料:
--   [1] ISO/IEC 9075-2:2023 - SQL/Foundation - Sequence Generators
--       https://www.iso.org/standard/76584.html
--   [2] SQL Standard - Wikipedia
--       https://en.wikipedia.org/wiki/SQL:2023

-- ============================================
-- SEQUENCE (SQL:2003)
-- ============================================
CREATE SEQUENCE user_id_seq
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE;

-- NEXT VALUE FOR（SQL:2003 标准语法）
SELECT NEXT VALUE FOR user_id_seq;

INSERT INTO users (id, username) VALUES (NEXT VALUE FOR user_id_seq, 'alice');

-- 修改序列
ALTER SEQUENCE user_id_seq RESTART WITH 1000;

-- 删除序列
DROP SEQUENCE user_id_seq CASCADE;
DROP SEQUENCE user_id_seq RESTRICT;

-- ============================================
-- IDENTITY 列 (SQL:2003)
-- ============================================
-- GENERATED ALWAYS AS IDENTITY
CREATE TABLE users (
    id       BIGINT GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(64) NOT NULL,
    email    VARCHAR(255) NOT NULL
);

-- GENERATED BY DEFAULT AS IDENTITY
CREATE TABLE orders (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    amount   DECIMAL(10,2)
);

-- 带参数的 IDENTITY
CREATE TABLE products (
    id       BIGINT GENERATED ALWAYS AS IDENTITY
                    (START WITH 1 INCREMENT BY 1),
    name     VARCHAR(64)
);

-- 覆盖 GENERATED ALWAYS
INSERT INTO users (id, username, email)
    OVERRIDING SYSTEM VALUE
    VALUES (999, 'admin', 'admin@example.com');

-- 覆盖 GENERATED BY DEFAULT
INSERT INTO orders (id, amount)
    OVERRIDING USER VALUE
    VALUES (NULL, 99.99);

-- ============================================
-- 标准中未定义的功能
-- ============================================
-- 以下是各数据库扩展，非 SQL 标准：
-- AUTO_INCREMENT (MySQL)
-- SERIAL / BIGSERIAL (PostgreSQL)
-- AUTOINCREMENT (SQLite)
-- UUID 生成函数

-- ============================================
-- 序列 vs 自增 权衡
-- ============================================
-- SQL 标准定义了两种机制：
-- 1. SEQUENCE（SQL:2003）：独立对象，可跨表共享
-- 2. IDENTITY（SQL:2003）：列级自动生成
-- 3. GENERATED ALWAYS：数据库完全控制
-- 4. GENERATED BY DEFAULT：允许手动覆盖
-- 5. OVERRIDING SYSTEM VALUE / OVERRIDING USER VALUE 控制覆盖行为
