-- Teradata: Sequences & Auto-Increment
--
-- 参考资料:
--   [1] Teradata Documentation - Identity Columns
--       https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Definition-Language-Syntax-and-Examples/Table-Statements/CREATE-TABLE
--   [2] Teradata Documentation - CREATE SEQUENCE (Teradata 17+)
--       https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Definition-Language-Syntax-and-Examples

-- ============================================
-- IDENTITY 列
-- ============================================
-- GENERATED ALWAYS
CREATE TABLE users (
    id       BIGINT GENERATED ALWAYS AS IDENTITY
                    (START WITH 1 INCREMENT BY 1),
    username VARCHAR(64) NOT NULL,
    email    VARCHAR(255) NOT NULL
) PRIMARY INDEX (id);

-- GENERATED BY DEFAULT
CREATE TABLE orders (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    amount   DECIMAL(10,2)
) PRIMARY INDEX (id);

-- 带参数
CREATE TABLE products (
    id       BIGINT GENERATED ALWAYS AS IDENTITY
                    (START WITH 100 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999 NO CYCLE),
    name     VARCHAR(64)
) PRIMARY INDEX (id);

-- ============================================
-- SEQUENCE（Teradata 17+）
-- ============================================
-- Teradata 17+ 版本支持 CREATE SEQUENCE
-- CREATE SEQUENCE user_id_seq
--     START WITH 1
--     INCREMENT BY 1
--     CACHE 20;
-- SELECT NEXT VALUE FOR user_id_seq;

-- ============================================
-- 替代方案（早期版本）
-- ============================================

-- 方法 1：使用 ROW_NUMBER()
SELECT
    ROW_NUMBER() OVER (ORDER BY created_at) AS row_id,
    username,
    email
FROM users;

-- 方法 2：使用 HASHROW()（生成确定性哈希值）
SELECT HASHROW(username, email) AS hash_id, username, email
FROM users;

-- 方法 3：使用 RANDOM() 生成随机值（不推荐作为主键）

-- ============================================
-- UUID 生成
-- Teradata 没有内置 UUID 函数
-- ============================================
-- 替代方案：使用 UDF 或应用层生成

-- ============================================
-- 序列 vs 自增 权衡
-- ============================================
-- 1. IDENTITY：Teradata 推荐的自增方式
-- 2. SEQUENCE（17+）：灵活，可跨表共享
-- 3. ROW_NUMBER()：查询时生成序号
-- 4. Teradata 是 MPP 架构，PRIMARY INDEX 选择影响数据分布
-- 5. 不建议用自增列作为 PRIMARY INDEX（会导致数据倾斜）

-- 限制：
-- SEQUENCE 需要 Teradata 17+
-- 不支持 AUTO_INCREMENT / SERIAL
-- 没有内置 UUID 函数
-- IDENTITY 列不应作为 PRIMARY INDEX（数据分布不均）
