-- YugabyteDB: Sequences & Auto-Increment
--
-- 参考资料:
--   [1] YugabyteDB Documentation - CREATE SEQUENCE
--       https://docs.yugabyte.com/latest/api/ysql/the-sql-language/statements/ddl_create_sequence/
--   [2] YugabyteDB Documentation - Serial Types
--       https://docs.yugabyte.com/latest/api/ysql/datatypes/type_serial/
--   [3] YugabyteDB Documentation - UUID Functions
--       https://docs.yugabyte.com/latest/api/ysql/exprs/func_gen_random_uuid/

-- ============================================
-- SEQUENCE（兼容 PostgreSQL）
-- ============================================
CREATE SEQUENCE user_id_seq
    START WITH 1
    INCREMENT BY 1
    CACHE 100;                              -- 分布式环境中 CACHE 很重要

-- 使用序列
INSERT INTO users (id, username) VALUES (nextval('user_id_seq'), 'alice');
SELECT nextval('user_id_seq');
SELECT currval('user_id_seq');
SELECT setval('user_id_seq', 1000);

-- 修改序列
ALTER SEQUENCE user_id_seq RESTART WITH 1000;
ALTER SEQUENCE user_id_seq CACHE 1000;

-- 删除序列
DROP SEQUENCE user_id_seq;
DROP SEQUENCE IF EXISTS user_id_seq;

-- ============================================
-- SERIAL / BIGSERIAL
-- ============================================
CREATE TABLE users (
    id       BIGSERIAL PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    email    VARCHAR(255) NOT NULL
);

-- ============================================
-- GENERATED AS IDENTITY
-- ============================================
CREATE TABLE orders (
    id       BIGINT GENERATED ALWAYS AS IDENTITY,
    amount   DECIMAL(10,2)
);

CREATE TABLE products (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1),
    name     VARCHAR(64)
);

-- ============================================
-- UUID 生成（推荐用于分布式主键）
-- ============================================
SELECT gen_random_uuid();                    -- 内置，无需扩展

CREATE TABLE sessions (
    id         UUID DEFAULT gen_random_uuid(),
    user_id    BIGINT,
    created_at TIMESTAMP DEFAULT current_timestamp
);

-- uuid-ossp 扩展
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
SELECT uuid_generate_v4();

-- ============================================
-- 分布式 ID 策略
-- ============================================
-- YugabyteDB 分布式架构下的考量：
-- 1. UUID（推荐）：各节点独立生成，无跨节点协调
-- 2. SEQUENCE + CACHE：减少跨节点协调，但值可能不连续
-- 3. SERIAL：内部使用序列，有分布式开销
-- 4. HASH 分片：使用 HASH 分片的表，UUID 主键分布最均匀

-- YugabyteDB 特有的序列行为：
-- CACHE 值影响性能：每个 TServer 缓存 CACHE 个序列值
-- 默认 CACHE = 1，分布式环境建议设置更大值（100+）

-- ============================================
-- 序列 vs 自增 权衡
-- ============================================
-- 1. UUID（推荐分布式）：无热点，无协调开销
-- 2. SEQUENCE + 高 CACHE：性能平衡，值不连续
-- 3. SERIAL/BIGSERIAL：兼容 PostgreSQL 但有分布式开销
-- 4. GENERATED AS IDENTITY：SQL 标准兼容
-- 5. YSQL 兼容 PostgreSQL，但分布式语义不同
