-- Firebird: JSON 展平为关系行 (JSON Flatten)
--
-- 参考资料:
--   [1] Firebird 4.0 不原生支持 JSON 类型
--       https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html
--   [2] Firebird 5.0 计划增加 JSON 支持

-- ============================================================
-- 注意: Firebird 目前没有原生 JSON 函数
-- ============================================================
-- 建议方案:
-- 1. 在应用层解析 JSON
-- 2. 使用 UDF（用户自定义函数）扩展
-- 3. 将 JSON 数据预处理为关系表

-- 简单的 JSON 值提取（用字符串函数模拟，仅适用于简单场景）
-- 这种方法不可靠，仅用于演示
CREATE TABLE orders_json (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data VARCHAR(10000)
);

-- 使用 SUBSTRING + POSITION 手动解析（不推荐用于生产）
SELECT id,
       SUBSTRING(data FROM POSITION('"customer":"' IN data) + 12
                      FOR POSITION('"' IN SUBSTRING(data FROM POSITION('"customer":"' IN data) + 12)) - 1
       ) AS customer
FROM   orders_json;
-- 强烈建议在应用层处理 JSON 或等待 Firebird 5.0
