-- Firebird: ALTER TABLE
--
-- 参考资料:
--   [1] Firebird SQL Reference
--       https://firebirdsql.org/en/reference-manuals/
--   [2] Firebird Release Notes
--       https://firebirdsql.org/file/documentation/release_notes/html/en/4_0/rlsnotes40.html

-- Add column
ALTER TABLE users ADD phone VARCHAR(20);

-- Add column with default
ALTER TABLE users ADD status INTEGER DEFAULT 1 NOT NULL;

-- Add column at specific position
ALTER TABLE users ADD city VARCHAR(64) AFTER email;
-- Note: AFTER/BEFORE changes logical position only; physical position unchanged

-- Modify column type
ALTER TABLE users ALTER phone TYPE VARCHAR(32);

-- Rename column (2.5+)
ALTER TABLE users ALTER phone TO mobile;

-- Drop column
ALTER TABLE users DROP phone;

-- Set / drop default
ALTER TABLE users ALTER status SET DEFAULT 0;
ALTER TABLE users ALTER status DROP DEFAULT;

-- Set / drop NOT NULL (2.0+)
ALTER TABLE users ALTER phone SET NOT NULL;
ALTER TABLE users ALTER phone DROP NOT NULL;

-- Add computed column
ALTER TABLE users ADD full_name COMPUTED BY (first_name || ' ' || last_name);

-- Multiple operations in one statement
-- Note: Firebird processes each clause sequentially in a single ALTER TABLE
ALTER TABLE users
    ADD phone VARCHAR(20),
    ADD city VARCHAR(64),
    DROP country;

-- Rename table (not directly supported; workaround below)
-- Firebird does not have RENAME TABLE; use system table update (not recommended)
-- Preferred approach: create new table, copy data, drop old table

-- Add IDENTITY (4.0+)
ALTER TABLE users ALTER id SET GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE users ALTER id RESTART WITH 1000;

-- Change character set
ALTER TABLE users ALTER name TYPE VARCHAR(100) CHARACTER SET UTF8;

-- Drop constraint and re-add
ALTER TABLE users DROP CONSTRAINT uk_email;
ALTER TABLE users ADD CONSTRAINT uk_email UNIQUE (email);

-- RECREATE TABLE (drop and recreate if exists)
-- Note: this is a DDL shortcut, not an ALTER
RECREATE TABLE temp_work (
    id   INTEGER NOT NULL PRIMARY KEY,
    data VARCHAR(200)
);
