-- DamengDB (达梦): 日期函数
-- Oracle compatible syntax.
--
-- 参考资料:
--   [1] DamengDB SQL Reference
--       https://eco.dameng.com/document/dm/zh-cn/sql-dev/index.html
--   [2] DamengDB System Admin Manual
--       https://eco.dameng.com/document/dm/zh-cn/pm/index.html

-- 当前日期时间
SELECT SYSDATE FROM DUAL;
SELECT SYSTIMESTAMP FROM DUAL;
SELECT CURRENT_TIMESTAMP FROM DUAL;
SELECT CURRENT_DATE FROM DUAL;
SELECT LOCALTIMESTAMP FROM DUAL;

-- 构造日期
SELECT TO_DATE('2024-01-15', 'YYYY-MM-DD') FROM DUAL;
SELECT TO_TIMESTAMP('2024-01-15 10:30:00', 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;
SELECT TO_DATE('15-JAN-2024', 'DD-MON-YYYY') FROM DUAL;

-- 日期加减
SELECT SYSDATE + 1 FROM DUAL;                    -- 加 1 天
SELECT SYSDATE + INTERVAL '3' MONTH FROM DUAL;
SELECT SYSDATE - INTERVAL '2' HOUR FROM DUAL;
SELECT ADD_MONTHS(SYSDATE, 3) FROM DUAL;
SELECT ADD_MONTHS(SYSDATE, -6) FROM DUAL;

-- 日期差
SELECT TO_DATE('2024-12-31', 'YYYY-MM-DD') - TO_DATE('2024-01-01', 'YYYY-MM-DD') FROM DUAL;
SELECT MONTHS_BETWEEN(
    TO_DATE('2024-12-31', 'YYYY-MM-DD'),
    TO_DATE('2024-01-01', 'YYYY-MM-DD')
) FROM DUAL;

-- 提取
SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL;
SELECT EXTRACT(MONTH FROM SYSDATE) FROM DUAL;
SELECT EXTRACT(DAY FROM SYSDATE) FROM DUAL;
SELECT EXTRACT(HOUR FROM SYSTIMESTAMP) FROM DUAL;

-- 格式化
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'Day, Month DD, YYYY') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'HH12:MI AM') FROM DUAL;

-- 截断
SELECT TRUNC(SYSDATE) FROM DUAL;                 -- 去掉时间部分
SELECT TRUNC(SYSDATE, 'MM') FROM DUAL;           -- 月初
SELECT TRUNC(SYSDATE, 'YY') FROM DUAL;           -- 年初

-- 四舍五入
SELECT ROUND(SYSDATE, 'MM') FROM DUAL;           -- 四舍五入到月
SELECT ROUND(SYSDATE, 'YY') FROM DUAL;           -- 四舍五入到年

-- LAST_DAY / NEXT_DAY
SELECT LAST_DAY(SYSDATE) FROM DUAL;
SELECT NEXT_DAY(SYSDATE, 'MONDAY') FROM DUAL;

-- 注意事项：
-- 日期函数与 Oracle 兼容
-- SYSDATE 返回 DATE 类型（含时分秒）
-- SYSTIMESTAMP 返回 TIMESTAMP 类型
-- 支持 ADD_MONTHS、MONTHS_BETWEEN 等 Oracle 函数
-- 支持 TRUNC 和 ROUND 截断日期
