-- IBM Db2: Date Functions
--
-- 参考资料:
--   [1] Db2 SQL Reference
--       https://www.ibm.com/docs/en/db2/11.5?topic=sql
--   [2] Db2 Built-in Functions
--       https://www.ibm.com/docs/en/db2/11.5?topic=functions-built-in

-- Current date/time
SELECT CURRENT DATE FROM SYSIBM.SYSDUMMY1;
SELECT CURRENT TIME FROM SYSIBM.SYSDUMMY1;
SELECT CURRENT TIMESTAMP FROM SYSIBM.SYSDUMMY1;
-- Note: Db2 uses space (CURRENT DATE), also accepts underscore (CURRENT_DATE)

-- Date construction
SELECT DATE('2024-01-15') FROM SYSIBM.SYSDUMMY1;
SELECT TIMESTAMP('2024-01-15 10:30:00') FROM SYSIBM.SYSDUMMY1;
SELECT TIME('10:30:00') FROM SYSIBM.SYSDUMMY1;
SELECT TO_DATE('2024-01-15', 'YYYY-MM-DD') FROM SYSIBM.SYSDUMMY1;

-- Date arithmetic (labeled durations, Db2-specific)
SELECT CURRENT DATE + 1 DAY FROM SYSIBM.SYSDUMMY1;
SELECT CURRENT DATE + 3 MONTHS FROM SYSIBM.SYSDUMMY1;
SELECT CURRENT DATE - 1 YEAR FROM SYSIBM.SYSDUMMY1;
SELECT CURRENT DATE + 2 YEARS + 3 MONTHS + 5 DAYS FROM SYSIBM.SYSDUMMY1;
SELECT CURRENT TIMESTAMP + 2 HOURS FROM SYSIBM.SYSDUMMY1;
SELECT CURRENT TIMESTAMP - 30 MINUTES FROM SYSIBM.SYSDUMMY1;

-- ADD_MONTHS (Db2 11.1+)
SELECT ADD_MONTHS(CURRENT DATE, 3) FROM SYSIBM.SYSDUMMY1;

-- Date difference
SELECT DAYS('2024-12-31') - DAYS('2024-01-01') FROM SYSIBM.SYSDUMMY1;  -- 365 days

-- TIMESTAMPDIFF (returns estimated difference)
-- Unit codes: 1=fractions, 2=seconds, 4=minutes, 8=hours, 16=days, 32=weeks, 64=months, 256=years
SELECT TIMESTAMPDIFF(16, CHAR(TIMESTAMP('2024-12-31-00.00.00') - TIMESTAMP('2024-01-01-00.00.00')))
FROM SYSIBM.SYSDUMMY1;

-- Extract (Db2 11.1+)
SELECT EXTRACT(YEAR FROM CURRENT DATE) FROM SYSIBM.SYSDUMMY1;
SELECT EXTRACT(MONTH FROM CURRENT DATE) FROM SYSIBM.SYSDUMMY1;

-- Legacy extraction functions (all versions)
SELECT YEAR(CURRENT DATE) FROM SYSIBM.SYSDUMMY1;
SELECT MONTH(CURRENT DATE) FROM SYSIBM.SYSDUMMY1;
SELECT DAY(CURRENT DATE) FROM SYSIBM.SYSDUMMY1;
SELECT HOUR(CURRENT TIMESTAMP) FROM SYSIBM.SYSDUMMY1;
SELECT MINUTE(CURRENT TIMESTAMP) FROM SYSIBM.SYSDUMMY1;
SELECT SECOND(CURRENT TIMESTAMP) FROM SYSIBM.SYSDUMMY1;
SELECT DAYOFWEEK(CURRENT DATE) FROM SYSIBM.SYSDUMMY1;       -- 1=Sunday
SELECT DAYOFYEAR(CURRENT DATE) FROM SYSIBM.SYSDUMMY1;
SELECT DAYNAME(CURRENT DATE) FROM SYSIBM.SYSDUMMY1;         -- 'Monday'
SELECT MONTHNAME(CURRENT DATE) FROM SYSIBM.SYSDUMMY1;       -- 'January'
SELECT WEEK(CURRENT DATE) FROM SYSIBM.SYSDUMMY1;
SELECT QUARTER(CURRENT DATE) FROM SYSIBM.SYSDUMMY1;

-- Formatting
SELECT VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') FROM SYSIBM.SYSDUMMY1;
SELECT TO_CHAR(CURRENT TIMESTAMP, 'YYYY-MM-DD') FROM SYSIBM.SYSDUMMY1;  -- Db2 11.1+
SELECT TO_CHAR(CURRENT DATE, 'Day, Month DD, YYYY') FROM SYSIBM.SYSDUMMY1;

-- Truncation
SELECT TRUNC(CURRENT TIMESTAMP, 'DD') FROM SYSIBM.SYSDUMMY1;  -- to day
SELECT TRUNC(CURRENT TIMESTAMP, 'MM') FROM SYSIBM.SYSDUMMY1;  -- to month
SELECT TRUNC(CURRENT TIMESTAMP, 'YY') FROM SYSIBM.SYSDUMMY1;  -- to year

-- LAST_DAY
SELECT LAST_DAY(CURRENT DATE) FROM SYSIBM.SYSDUMMY1;

-- NEXT_DAY
SELECT NEXT_DAY(CURRENT DATE, 'MONDAY') FROM SYSIBM.SYSDUMMY1;

-- MIDNIGHT_SECONDS (seconds since midnight)
SELECT MIDNIGHT_SECONDS(CURRENT TIME) FROM SYSIBM.SYSDUMMY1;

-- Julian day
SELECT JULIAN_DAY(CURRENT DATE) FROM SYSIBM.SYSDUMMY1;

-- Note: labeled durations (+ 1 DAY, + 3 MONTHS) are Db2's primary date arithmetic
-- Note: SYSIBM.SYSDUMMY1 is the single-row table (like DUAL)
-- Note: Db2 timestamp format uses dashes and dots internally
