-- H2: 日期时间类型
--
-- 参考资料:
--   [1] H2 SQL Reference - Commands
--       https://h2database.com/html/commands.html
--   [2] H2 - Data Types
--       https://h2database.com/html/datatypes.html
--   [3] H2 - Functions
--       https://h2database.com/html/functions.html

-- DATE: 日期
-- TIME: 时间（可带时区）
-- TIMESTAMP: 日期时间（可带时区）
-- INTERVAL: 时间间隔（年-月 或 天-秒）

CREATE TABLE events (
    id         IDENTITY,
    event_date DATE,
    event_time TIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE
);

-- 获取当前时间
SELECT CURRENT_DATE;
SELECT CURRENT_TIME;
SELECT CURRENT_TIMESTAMP;
SELECT LOCALTIMESTAMP;
SELECT NOW();

-- 日期运算
SELECT CURRENT_DATE + 7;                      -- 加 7 天
SELECT DATEADD('DAY', 7, CURRENT_DATE);
SELECT DATEADD('MONTH', 1, CURRENT_DATE);
SELECT DATEADD('HOUR', 3, CURRENT_TIMESTAMP);

-- 日期差
SELECT DATEDIFF('DAY', DATE '2024-01-01', DATE '2024-12-31');    -- 365
SELECT DATEDIFF('MONTH', DATE '2024-01-01', DATE '2024-06-15'); -- 5

-- 提取
SELECT EXTRACT(YEAR FROM CURRENT_DATE);
SELECT EXTRACT(MONTH FROM CURRENT_DATE);
SELECT EXTRACT(DAY FROM CURRENT_DATE);
SELECT EXTRACT(HOUR FROM CURRENT_TIMESTAMP);
SELECT YEAR(CURRENT_DATE);
SELECT MONTH(CURRENT_DATE);
SELECT DAY_OF_WEEK(CURRENT_DATE);
SELECT DAY_OF_YEAR(CURRENT_DATE);

-- 截断
SELECT TRUNCATE(CURRENT_TIMESTAMP TO DAY);
SELECT DATE_TRUNC('HOUR', CURRENT_TIMESTAMP);

-- 格式化
SELECT FORMATDATETIME(CURRENT_TIMESTAMP, 'yyyy-MM-dd HH:mm:ss');
SELECT FORMATDATETIME(CURRENT_TIMESTAMP, 'EEEE, dd MMMM yyyy');

-- 解析
SELECT PARSEDATETIME('2024-01-15 10:30:00', 'yyyy-MM-dd HH:mm:ss');
SELECT CAST('2024-01-15' AS DATE);

-- 注意：H2 支持完整的 SQL 标准日期时间类型
-- 注意：DATEADD/DATEDIFF 是常用函数
-- 注意：FORMATDATETIME/PARSEDATETIME 使用 Java 日期格式
-- 注意：支持 TIMESTAMP WITH TIME ZONE
