-- Firebird: 迁移速查表 (Migration Cheatsheet)
--
-- 参考资料:
--   [1] Firebird SQL Reference
--       https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/

-- 一、数据类型: 标准SQL类型
--   INT→INTEGER, BIGINT→BIGINT, FLOAT→FLOAT, DOUBLE→DOUBLE PRECISION,
--   VARCHAR→VARCHAR(n), TEXT→BLOB SUB_TYPE TEXT, DECIMAL→DECIMAL(p,s),
--   BOOLEAN→BOOLEAN(3.0+), DATE→DATE, TIMESTAMP→TIMESTAMP,
--   BLOB→BLOB, AUTO_INCREMENT→GENERATED BY DEFAULT AS IDENTITY(3.0+)
-- 二、陷阱: BLOB SUB_TYPE TEXT用于大文本, SEQUENCE(生成器)用于自增,
--   存储过程用PSQL语法, 字符集需显式指定, 页大小影响行大小限制
-- 三、自增: GENERATED BY DEFAULT AS IDENTITY 或 SEQUENCE
CREATE SEQUENCE my_seq;
-- 使用: NEXT VALUE FOR my_seq
-- 四、日期: CURRENT_TIMESTAMP; CURRENT_DATE; d + 1; DATEDIFF(DAY,a,b)
-- 五、字符串: CHAR_LENGTH, UPPER, LOWER, TRIM, SUBSTRING(s FROM p FOR n),
--   REPLACE, POSITION(sub IN s), ||
