-- Spanner: 迁移速查表 (Migration Cheatsheet)
--
-- 参考资料:
--   [1] Cloud Spanner SQL Reference
--       https://cloud.google.com/spanner/docs/reference/standard-sql/

-- 一、数据类型（到 Spanner）
--   INT→INT64, FLOAT→FLOAT64, VARCHAR→STRING(n), TEXT→STRING(MAX),
--   BOOLEAN→BOOL, DATE→DATE, TIMESTAMP→TIMESTAMP, BLOB→BYTES(MAX),
--   JSON→JSON, ARRAY→ARRAY<T>(原生支持), STRUCT→STRUCT<...>
-- 二、函数: 与BigQuery标准SQL类似
--   IFNULL→IFNULL/COALESCE, CONCAT→CONCAT, GENERATE_UUID可用
-- 三、陷阱: 全球分布式数据库, 主键设计很关键(避免热点),
--   不建议使用自增主键(推荐UUID或bit-reversed序列),
--   DDL和DML必须在不同事务中, interleaved tables是Spanner特色,
--   无AUTO_INCREMENT, SEQUENCE只在GoogleSQL方言支持
-- 四、自增: 无传统自增，推荐 GENERATE_UUID() 或 bit_reverse(SEQUENCE)
-- 五、日期: CURRENT_TIMESTAMP(); CURRENT_DATE(); DATE_ADD(d, INTERVAL 1 DAY);
--   DATE_DIFF(a,b,DAY); FORMAT_TIMESTAMP('%Y-%m-%d',ts)
--   PARSE_DATE('%Y-%m-%d', s); UNIX_SECONDS(ts); TIMESTAMP_SECONDS(epoch)
--   EXTRACT(YEAR FROM d); DATE_TRUNC(d, MONTH)
-- 六、字符串: LENGTH, UPPER, LOWER, TRIM, SUBSTR, REPLACE, STRPOS, CONCAT, STRING_AGG

-- ============================================================
-- 七、数据类型映射（从 MySQL/PostgreSQL/Oracle 到 Spanner）
-- ============================================================
-- MySQL → Spanner:
--   INT → INT64, BIGINT → INT64, FLOAT → FLOAT64,
--   DOUBLE → FLOAT64, DECIMAL → NUMERIC,
--   VARCHAR(n) → STRING(n), TEXT → STRING(MAX),
--   DATETIME → TIMESTAMP, DATE → DATE,
--   BOOLEAN → BOOL, BLOB → BYTES(MAX),
--   JSON → JSON, AUTO_INCREMENT → 不支持,
--   ARRAY → ARRAY<T> (原生支持)
-- PostgreSQL → Spanner:
--   INTEGER → INT64, TEXT → STRING(MAX),
--   SERIAL → 不支持, BOOLEAN → BOOL,
--   JSONB → JSON, BYTEA → BYTES(MAX),
--   ARRAY → ARRAY<T>
-- Oracle → Spanner:
--   NUMBER → INT64/NUMERIC, VARCHAR2 → STRING,
--   CLOB → STRING(MAX), DATE → TIMESTAMP,
--   SEQUENCE → bit_reverse(SEQUENCE)

-- 八、函数等价映射
-- MySQL → Spanner:
--   IFNULL → IFNULL/COALESCE, NOW() → CURRENT_TIMESTAMP(),
--   DATE_FORMAT → FORMAT_TIMESTAMP, CONCAT → CONCAT,
--   GROUP_CONCAT → STRING_AGG, LIMIT → LIMIT

-- 九、常见陷阱补充
--   全球分布式数据库（强一致性）
--   主键设计很关键（避免热点，不建议自增主键）
--   推荐 UUID 或 bit-reversed 序列
--   DDL 和 DML 必须在不同事务中
--   interleaved tables 是 Spanner 特色（父子表物理共存）
--   无 AUTO_INCREMENT
--   SEQUENCE 只在 GoogleSQL 方言支持
--   读写事务 vs 只读事务 性能差异大

-- 十、NULL 处理
-- IFNULL(a, b); COALESCE(a, b, c);
-- NULLIF(a, b);
-- IF(a IS NULL, b, a);

-- 十一、分页语法
-- SELECT * FROM t ORDER BY id LIMIT 10 OFFSET 20;

-- 十二、Interleaved Table 示例
-- CREATE TABLE Orders (
--   CustomerId INT64, OrderId INT64, ...
-- ) PRIMARY KEY (CustomerId, OrderId),
--   INTERLEAVE IN PARENT Customers ON DELETE CASCADE;
