-- Teradata: 迁移速查表 (Migration Cheatsheet)
--
-- 参考资料:
--   [1] Teradata SQL Reference
--       https://docs.teradata.com/r/Teradata-VantageTM-SQL-Functions-Expressions-and-Predicates

-- 一、数据类型（到 Teradata）
--   INT→INTEGER, BIGINT→BIGINT, FLOAT→FLOAT, DOUBLE→DOUBLE PRECISION,
--   VARCHAR→VARCHAR(n), TEXT→CLOB, DECIMAL→DECIMAL(p,s),
--   BOOLEAN→BYTEINT, DATE→DATE, TIMESTAMP→TIMESTAMP, BLOB→BLOB,
--   JSON→JSON(15.0+), AUTO_INCREMENT→GENERATED ALWAYS AS IDENTITY
-- 二、函数: IFNULL/NVL→COALESCE或NVL, NOW()→CURRENT_TIMESTAMP,
--   CONCAT→||或CONCAT, TOP→TOP或SAMPLE, LIMIT→TOP n 或 QUALIFY ROW_NUMBER
-- 三、陷阱: Teradata使用MPP架构(选择合适的PI-主索引很重要),
--   日期格式独特(DATE类型内部为INTEGER), 无AUTO_COMMIT(默认),
--   QUALIFY子句是Teradata特色(窗口函数过滤)
-- 四、自增: GENERATED ALWAYS AS IDENTITY
-- 五、日期: CURRENT_TIMESTAMP; CURRENT_DATE; d + INTERVAL '1' DAY;
--   CAST(ts AS FORMAT 'YYYY-MM-DD')
--   EXTRACT(YEAR FROM d); ADD_MONTHS(d,1);
--   TO_CHAR(d, 'YYYY-MM-DD'); TO_DATE(s, 'YYYY-MM-DD')
-- 六、字符串: CHARACTER_LENGTH, UPPER, LOWER, TRIM, SUBSTR, OREPLACE, INDEX, ||

-- ============================================================
-- 七、数据类型映射（从 Oracle/MySQL/PostgreSQL 到 Teradata）
-- ============================================================
-- Oracle → Teradata:
--   NUMBER(p,s) → DECIMAL(p,s)/INTEGER, VARCHAR2(n) → VARCHAR(n),
--   CLOB → CLOB, DATE → TIMESTAMP (Oracle DATE含时间),
--   TIMESTAMP → TIMESTAMP, BLOB → BLOB,
--   SYSDATE → CURRENT_TIMESTAMP, SEQUENCE → IDENTITY
-- MySQL → Teradata:
--   INT → INTEGER, BIGINT → BIGINT, FLOAT → FLOAT,
--   DOUBLE → DOUBLE PRECISION, VARCHAR(n) → VARCHAR(n),
--   TEXT → CLOB, DATETIME → TIMESTAMP, DATE → DATE,
--   BOOLEAN → BYTEINT (0/1), AUTO_INCREMENT → IDENTITY,
--   JSON → JSON (15.0+)
-- PostgreSQL → Teradata:
--   INTEGER → INTEGER, TEXT → CLOB, SERIAL → IDENTITY,
--   BOOLEAN → BYTEINT, JSONB → JSON

-- 八、函数等价映射
-- MySQL → Teradata:
--   IFNULL → COALESCE/NVL, NOW() → CURRENT_TIMESTAMP,
--   DATE_FORMAT → CAST(d AS FORMAT '...'),
--   CONCAT(a,b) → a || b, GROUP_CONCAT → 不直接支持,
--   LIMIT → TOP/SAMPLE/QUALIFY ROW_NUMBER()
-- 特有: QUALIFY 子句 (窗口函数过滤)

-- 九、常见陷阱补充
--   MPP 架构，PI (Primary Index) 选择很重要
--   日期格式独特（DATE 类型内部为 INTEGER）
--   默认无 AUTO_COMMIT（需显式 COMMIT）
--   QUALIFY 子句是 Teradata 特色
--   MERGE INTO 语法支持（UPSERT）
--   COLLECT STATISTICS 替代 ANALYZE
--   SET vs MULTISET 表（默认 SET 去重）

-- 十、NULL 处理
-- COALESCE(a, b, c); NVL(a, b);
-- NULLIF(a, b); ZEROIFNULL(a);                       -- NULL→0
-- NULLIFZERO(a);                                     -- 0→NULL

-- 十一、分页语法
-- SELECT TOP 10 * FROM t ORDER BY id;                -- 前 N 行
-- SELECT * FROM t SAMPLE 100;                        -- 采样
-- SELECT * FROM t QUALIFY ROW_NUMBER() OVER (ORDER BY id) BETWEEN 21 AND 30;
