-- TiDB: 迁移速查表 (Migration Cheatsheet)
--
-- 参考资料:
--   [1] TiDB Documentation - MySQL Compatibility
--       https://docs.pingcap.com/tidb/stable/mysql-compatibility
--   [2] TiDB Migration Guide
--       https://docs.pingcap.com/tidb/stable/migration-overview

-- 一、与 MySQL 的兼容性: 高度兼容 MySQL 5.7/8.0 语法
--   数据类型: 基本完全兼容MySQL
--   差异: AUTO_INCREMENT 行为不同(TiDB使用分布式自增,可能不连续),
--         部分MySQL特性不支持(如存储过程/触发器的部分功能)
-- 二、函数: 与MySQL基本兼容
--   差异: 部分MySQL特有函数可能不支持
-- 三、陷阱: 分布式架构(大事务有限制), AUTO_INCREMENT不保证连续,
--   TiKV存储引擎vs InnoDB行为差异, 乐观/悲观事务模式选择,
--   热点问题(需要合理设计主键), 不支持外键约束,
--   不支持FULLTEXT索引, 临时表语法差异
-- 四、自增: AUTO_INCREMENT（分布式自增，可能不连续）
--   推荐: AUTO_RANDOM 避免热点
-- 五、日期: NOW(); CURDATE(); DATE_ADD(NOW(),INTERVAL 1 DAY);
--   DATEDIFF(a,b); DATE_FORMAT(NOW(),'%Y-%m-%d %H:%i:%s')
--   UNIX_TIMESTAMP(); FROM_UNIXTIME(epoch);
--   STR_TO_DATE(s,'%Y-%m-%d'); EXTRACT(YEAR FROM d)
-- 六、字符串: CHAR_LENGTH, UPPER, LOWER, TRIM, SUBSTRING,
--   REPLACE, LOCATE, CONCAT, GROUP_CONCAT

-- ============================================================
-- 七、数据类型映射（从 MySQL 到 TiDB）
-- ============================================================
-- MySQL → TiDB: 高度兼容
--   所有 MySQL 数据类型基本直接支持
--   INT → INT, BIGINT → BIGINT, FLOAT → FLOAT,
--   DOUBLE → DOUBLE, DECIMAL → DECIMAL,
--   VARCHAR → VARCHAR, TEXT → TEXT, BLOB → BLOB,
--   DATE → DATE, DATETIME → DATETIME, TIMESTAMP → TIMESTAMP,
--   BOOLEAN → BOOLEAN (TINYINT(1) 别名),
--   JSON → JSON, ENUM → ENUM, SET → SET,
--   AUTO_INCREMENT → AUTO_INCREMENT (行为不同!)
-- 差异:
--   AUTO_INCREMENT 不保证连续（分布式自增）
--   推荐 AUTO_RANDOM 避免写入热点

-- 八、函数等价映射
-- MySQL → TiDB: 基本完全兼容
--   IFNULL, NOW(), DATE_FORMAT, STR_TO_DATE,
--   CONCAT, GROUP_CONCAT, LIMIT, OFFSET
-- 差异:
--   部分 MySQL 特有函数可能不支持
--   窗口函数完全支持

-- 九、常见陷阱补充
--   分布式架构（大事务有限制，默认 100MB）
--   AUTO_INCREMENT 不保证连续（使用分布式自增）
--   推荐 AUTO_RANDOM 主键避免热点
--   TiKV 存储引擎 vs InnoDB 行为差异
--   乐观/悲观事务模式选择（默认悲观 4.0+）
--   热点问题需要合理设计主键
--   不支持外键约束
--   不支持 FULLTEXT 索引
--   临时表语法差异
--   TiFlash 列存副本加速分析查询

-- 十、NULL 处理
-- IFNULL(a, b); COALESCE(a, b, c);
-- NULLIF(a, b); <=> (NULL安全等于);
-- ISNULL(a) 返回 0 或 1

-- 十一、分页语法
-- SELECT * FROM t ORDER BY id LIMIT 10 OFFSET 20;    -- 与 MySQL 相同
