-- KingbaseES (人大金仓): 数值类型
-- PostgreSQL compatible with Oracle-compatible extensions.
--
-- 参考资料:
--   [1] KingbaseES SQL Reference - Data Types
--       https://help.kingbase.com.cn/v8/index.html
--   [2] KingbaseES Oracle Compatibility Guide
--       https://help.kingbase.com.cn/v8/development/sql-plsql/oracle-compat.html
--   [3] PostgreSQL Documentation - Numeric Types
--       https://www.postgresql.org/docs/current/datatype-numeric.html

-- ============================================================
-- 1. 整数类型
-- ============================================================

-- SMALLINT / INT2:  2 字节，-32768 ~ 32767
-- INTEGER  / INT4:  4 字节，-2^31 ~ 2^31-1
-- BIGINT   / INT8:  8 字节，-2^63 ~ 2^63-1

CREATE TABLE examples (
    small_val SMALLINT,
    int_val   INTEGER,
    big_val   BIGINT
);

-- 设计特点（继承 PostgreSQL）:
--   (a) 无 UNSIGNED 类型: 与 PostgreSQL 一致，BIGINT 范围已足够
--   (b) 无 TINYINT: 与 PostgreSQL 一致，需要时用 SMALLINT 替代
--   (c) 无 MEDIUMINT: MySQL 独有，KingbaseES 不支持

-- ============================================================
-- 2. 自增序列类型
-- ============================================================

-- SERIAL 语法糖（传统方式，兼容 PostgreSQL）
CREATE TABLE t1 (id SERIAL PRIMARY KEY);       -- 4 字节
CREATE TABLE t2 (id BIGSERIAL PRIMARY KEY);    -- 8 字节
CREATE TABLE t3 (id SMALLSERIAL PRIMARY KEY);  -- 2 字节

-- IDENTITY（SQL 标准，推荐）
CREATE TABLE t4 (
    id  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id2 INTEGER GENERATED BY DEFAULT AS IDENTITY
);

-- Oracle 兼容模式下的序列:
-- 支持 CREATE SEQUENCE ... START WITH ... INCREMENT BY ...
-- 支持 seq_name.NEXTVAL / seq_name.CURRVAL 语法

-- ============================================================
-- 3. 定点数: NUMERIC / DECIMAL
-- ============================================================

-- NUMERIC(p,s) = DECIMAL(p,s): 完全等价
-- p = 总位数（最大 131072），s = 小数位数（最大 16383）
CREATE TABLE prices (
    price   NUMERIC(10,2),    -- 精确到分（8位整数+2位小数）
    amount  NUMERIC           -- 不指定精度: 任意精度
);

-- NUMERIC 的内部实现:
--   可变长存储（varlena），以 10000 进制存储数字
--   精确算术，无浮点精度问题
--   比 FLOAT 慢 ~10-50x（软件模拟 vs 硬件 FPU）

-- ============================================================
-- 4. Oracle 兼容数值类型
-- ============================================================

-- NUMBER(p,s): Oracle 兼容模式下的数值类型
-- 功能与 NUMERIC(p,s) 等价
-- Oracle 迁移时自动映射 Oracle NUMBER 到 KingbaseES NUMBER
CREATE TABLE oracle_compat (
    id      NUMBER(10),           -- Oracle 风格整数
    salary  NUMBER(12,2),         -- Oracle 风格定点数
    ratio   NUMBER                -- Oracle 风格任意精度
);

-- NUMBER vs NUMERIC 的区别:
--   功能上完全等价，都是任意精度定点数
--   NUMBER 是 Oracle 兼容别名，内部实现相同
--   Oracle 迁移场景建议使用 NUMBER 保持 SQL 兼容
--   新项目建议使用 NUMERIC（PostgreSQL 标准）

-- BINARY_DOUBLE / BINARY_FLOAT: Oracle 兼容浮点类型
-- BINARY_FLOAT:  4 字节（等价于 REAL / FLOAT4）
-- BINARY_DOUBLE: 8 字节（等价于 DOUBLE PRECISION / FLOAT8）

-- ============================================================
-- 5. 浮点数
-- ============================================================

-- REAL / FLOAT4:             4 字节，约 6 位有效数字
-- DOUBLE PRECISION / FLOAT8: 8 字节，约 15 位有效数字

SELECT 0.1::FLOAT + 0.2::FLOAT;     -- 0.30000000000000004 (IEEE 754 精度问题)
SELECT 0.1::NUMERIC + 0.2::NUMERIC; -- 0.3 (精确)

-- 特殊值
SELECT 'NaN'::NUMERIC;                -- Not a Number
SELECT 'Infinity'::DOUBLE PRECISION;  -- 正无穷
SELECT '-Infinity'::DOUBLE PRECISION; -- 负无穷

-- ============================================================
-- 6. 布尔类型
-- ============================================================

CREATE TABLE flags (active BOOLEAN DEFAULT TRUE);

-- BOOLEAN: 1 字节存储，值为 TRUE / FALSE / NULL
-- 继承 PostgreSQL 的真正布尔类型（非 MySQL 的 TINYINT 别名）
-- WHERE 中直接使用: WHERE active（等同于 WHERE active = TRUE）

-- ============================================================
-- 7. 数值类型的隐式转换规则
-- ============================================================

-- 提升链: SMALLINT → INTEGER → BIGINT → NUMERIC → REAL → DOUBLE PRECISION
SELECT 1::SMALLINT + 1::INTEGER;        -- INTEGER
SELECT 1::INTEGER + 1::BIGINT;          -- BIGINT
SELECT 1::INTEGER + 1.5::NUMERIC;       -- NUMERIC
SELECT 1::INTEGER + 1.5::FLOAT;         -- DOUBLE PRECISION

-- NUMBER 类型的提升:
-- NUMBER 与 NUMERIC 在类型提升链中处于同一位置
-- NUMBER + INTEGER → NUMBER
-- NUMBER + FLOAT → DOUBLE PRECISION

-- ============================================================
-- 8. KingbaseES 特有的数值功能
-- ============================================================

-- 8.1 数学函数增强
-- 继承 PostgreSQL 全部数学函数，Oracle 兼容模式下额外支持:
--   TRUNC(n, d):     Oracle 风格截断（PostgreSQL 用 TRUNCATE）
--   CEIL / FLOOR:    向上/向下取整（两种风格均支持）
--   ROUND(n, d):     四舍五入
--   MOD(m, n):       取模（Oracle 风格，PostgreSQL 也支持 % 运算符）
--   POWER(x, y):     幂运算
--   SQRT(n):         平方根
--   ABS(n):          绝对值
--   SIGN(n):         符号函数

-- 8.2 货币计算
-- 金融场景必须使用 NUMERIC / NUMBER（精确计算）
-- FLOAT / DOUBLE PRECISION 存在 IEEE 754 精度问题
-- 示例: 存储人民币金额
CREATE TABLE financial_records (
    id        BIGSERIAL PRIMARY KEY,
    amount    NUMERIC(18,2),          -- 金额，精确到分
    rate      NUMERIC(10,6),          -- 汇率，精确到小数点后6位
    quantity  INTEGER                  -- 数量
);

-- ============================================================
-- 9. 横向对比: 数值类型差异
-- ============================================================

-- 整数类型:
--   KingbaseES: SMALLINT(2), INTEGER(4), BIGINT(8)，无 UNSIGNED
--   PostgreSQL: SMALLINT(2), INTEGER(4), BIGINT(8)，无 UNSIGNED
--   Oracle:     NUMBER(p) 是唯一数值类型（INT 是 NUMBER(38) 别名）
--   MySQL:      TINYINT(1), SMALLINT(2), MEDIUMINT(3), INT(4), BIGINT(8)，有 UNSIGNED
--   达梦:       SMALLINT(2), INTEGER(4), BIGINT(8)，有 UNSIGNED 兼容
--
-- 精确小数:
--   KingbaseES: NUMERIC（任意精度 p≤131072）+ NUMBER（Oracle 兼容）
--   PostgreSQL: NUMERIC（任意精度 p≤131072）
--   Oracle:     NUMBER（任意精度）
--   MySQL:      DECIMAL（p≤65）
--   达梦:       DECIMAL/NUMBER（p≤38）
--
-- 布尔:
--   KingbaseES: 真正的 BOOLEAN (TRUE/FALSE)
--   PostgreSQL: 真正的 BOOLEAN
--   Oracle:     SQL 无布尔
--   MySQL:      TINYINT(1) 别名

-- ============================================================
-- 10. 注意事项与最佳实践
-- ============================================================

-- 1. 数值类型与 PostgreSQL 完全兼容，可无缝迁移
-- 2. Oracle 兼容模式下支持 NUMBER 类型，Oracle 迁移直接使用
-- 3. 不支持 UNSIGNED 类型，需要时用更大类型替代（如 INT → BIGINT）
-- 4. SERIAL 类型实际创建序列，推荐使用 IDENTITY（SQL 标准）
-- 5. 金融计算必须用 NUMERIC / NUMBER，避免浮点精度问题
-- 6. 整数溢出严格报错（与 PostgreSQL 一致）
-- 7. NUMBER 是 Oracle 兼容别名，内部与 NUMERIC 完全相同
-- 8. 混合 NUMERIC 和 FLOAT 运算会丢失精度，避免混合使用
