-- PostgreSQL: 数值类型
--
-- 参考资料:
--   [1] PostgreSQL Documentation - Numeric Types
--       https://www.postgresql.org/docs/current/datatype-numeric.html
--   [2] PostgreSQL Documentation - Mathematical Functions
--       https://www.postgresql.org/docs/current/functions-math.html

-- 整数
-- SMALLINT / INT2:  2 字节，-32768 ~ 32767
-- INTEGER / INT4:   4 字节，-2^31 ~ 2^31-1
-- BIGINT / INT8:    8 字节，-2^63 ~ 2^63-1

CREATE TABLE examples (
    small_val  SMALLINT,
    int_val    INTEGER,
    big_val    BIGINT
);

-- 注意：没有 UNSIGNED 类型，也没有 TINYINT 和 MEDIUMINT

-- 自增序列类型
-- SMALLSERIAL: 2 字节自增
-- SERIAL:      4 字节自增（非真正的类型，是创建 SEQUENCE 的语法糖）
-- BIGSERIAL:   8 字节自增
CREATE TABLE t (id SERIAL PRIMARY KEY);

-- 10+: IDENTITY（SQL 标准，推荐替代 SERIAL）
CREATE TABLE t (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id2 INTEGER GENERATED BY DEFAULT AS IDENTITY
);

-- 浮点数
-- REAL / FLOAT4:             4 字节，约 6 位有效数字
-- DOUBLE PRECISION / FLOAT8: 8 字节，约 15 位有效数字

-- 定点数（精确）
-- NUMERIC(p,s) / DECIMAL(p,s): 可变长度，最大 131072 位整数 + 16383 位小数
-- NUMERIC 不指定精度：任意精度
CREATE TABLE prices (
    price    NUMERIC(10,2),            -- 精确到分
    any_num  NUMERIC                   -- 任意精度
);

-- 布尔（真正的布尔类型）
CREATE TABLE t (active BOOLEAN DEFAULT TRUE);
-- 值: TRUE / FALSE / NULL

-- 特殊数值
SELECT 'NaN'::NUMERIC;                -- Not a Number
SELECT 'Infinity'::DOUBLE PRECISION;  -- 正无穷
SELECT '-Infinity'::DOUBLE PRECISION; -- 负无穷

-- 货币类型（不推荐，建议用 NUMERIC）
-- MONEY: 8 字节，受 lc_monetary 影响
