-- PostgreSQL: 数值类型
--
-- 参考资料:
--   [1] PostgreSQL Documentation - Numeric Types
--       https://www.postgresql.org/docs/current/datatype-numeric.html
--   [2] PostgreSQL Source - numeric.c
--       https://github.com/postgres/postgres/blob/master/src/backend/utils/adt/numeric.c

-- ============================================================
-- 1. 整数类型
-- ============================================================

-- SMALLINT / INT2:  2 字节，-32768 ~ 32767
-- INTEGER  / INT4:  4 字节，-2^31 ~ 2^31-1
-- BIGINT   / INT8:  8 字节，-2^63 ~ 2^63-1

CREATE TABLE examples (
    small_val SMALLINT,
    int_val   INTEGER,
    big_val   BIGINT
);

-- 设计特点:
--   (a) 无 UNSIGNED 类型: PostgreSQL 设计者认为 UNSIGNED 增加类型复杂度，
--       BIGINT (8字节) 的范围已足够覆盖 MySQL UNSIGNED INT 的使用场景。
--       对比: MySQL 有 UNSIGNED（最大值翻倍），PostgreSQL 用更大类型替代。
--   (b) 无 TINYINT: PostgreSQL 没有 1 字节整数类型。
--       替代: SMALLINT (2字节)，或布尔值用 BOOLEAN。
--   (c) 无 MEDIUMINT: MySQL 有 3 字节 MEDIUMINT，PostgreSQL 没有。
--       PostgreSQL 不做"节省字节"的类型细分——简化类型系统。

-- ============================================================
-- 2. 自增序列类型
-- ============================================================

-- SERIAL 语法糖（传统方式）
CREATE TABLE t1 (id SERIAL PRIMARY KEY);       -- 4 字节
CREATE TABLE t2 (id BIGSERIAL PRIMARY KEY);    -- 8 字节

-- IDENTITY（10+，SQL 标准，推荐）
CREATE TABLE t3 (
    id  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id2 INTEGER GENERATED BY DEFAULT AS IDENTITY
);

-- 详见 ddl/sequences/postgres.sql

-- ============================================================
-- 3. 定点数: NUMERIC / DECIMAL
-- ============================================================

-- NUMERIC(p,s) = DECIMAL(p,s): 完全等价
-- p = 总位数（最大 131072），s = 小数位数（最大 16383）
CREATE TABLE prices (
    price   NUMERIC(10,2),    -- 精确到分（8位整数+2位小数）
    amount  NUMERIC           -- 不指定精度: 任意精度（无限制!）
);

-- NUMERIC 的内部实现:
--   可变长存储（varlena），以 10000 进制（4位一组）存储数字。
--   每组占 int16 (2字节) + 头部信息。
--   好处: 精确算术，无浮点精度问题。
--   代价: 比 FLOAT 慢 ~10-50x（软件模拟 vs 硬件 FPU）。
--
-- 对比:
--   MySQL DECIMAL:     也是精确算术，但限制 p ≤ 65
--   Oracle NUMBER:     任意精度，类似 PostgreSQL NUMERIC
--   SQL Server DECIMAL: p ≤ 38

-- ============================================================
-- 4. 浮点数
-- ============================================================

-- REAL / FLOAT4:             4 字节，约 6 位有效数字
-- DOUBLE PRECISION / FLOAT8: 8 字节，约 15 位有效数字

SELECT 0.1::FLOAT + 0.2::FLOAT;  -- 0.30000000000000004 (IEEE 754 精度问题!)
SELECT 0.1::NUMERIC + 0.2::NUMERIC; -- 0.3 (精确)

-- 特殊值
SELECT 'NaN'::NUMERIC;                -- Not a Number
SELECT 'Infinity'::DOUBLE PRECISION;  -- 正无穷
SELECT '-Infinity'::DOUBLE PRECISION; -- 负无穷

-- 设计选择: REAL vs DOUBLE PRECISION vs NUMERIC
--   金融/货币: 必须用 NUMERIC（精确）
--   科学计算: DOUBLE PRECISION（快，精度足够）
--   机器学习: REAL/FLOAT4（节省内存/存储）
--   PostgreSQL 的 MONEY 类型存在但不推荐（受 lc_monetary 影响）

-- ============================================================
-- 5. 布尔类型: PostgreSQL 的真正 BOOLEAN
-- ============================================================

CREATE TABLE flags (active BOOLEAN DEFAULT TRUE);

-- PostgreSQL 的 BOOLEAN 是真正的布尔类型:
-- 值: TRUE, FALSE, NULL
-- 占 1 字节存储
-- WHERE 中可以直接使用: WHERE active（等同于 WHERE active = TRUE）

-- 对比:
--   MySQL:      BOOLEAN = TINYINT(1)（0/1 的别名，不是真正的布尔）
--   Oracle:     SQL 中无 BOOLEAN 类型（PL/SQL 有）
--   SQL Server: BIT（0/1/NULL，功能上类似布尔）

-- ============================================================
-- 6. 数值类型的隐式转换规则
-- ============================================================

-- 提升链: SMALLINT → INTEGER → BIGINT → NUMERIC → REAL → DOUBLE PRECISION
SELECT 1::SMALLINT + 1::INTEGER;        -- INTEGER
SELECT 1::INTEGER + 1::BIGINT;          -- BIGINT
SELECT 1::INTEGER + 1.5::NUMERIC;       -- NUMERIC
SELECT 1::INTEGER + 1.5::FLOAT;         -- DOUBLE PRECISION

-- 混合 NUMERIC 和 FLOAT:
SELECT 1::NUMERIC + 1.5::FLOAT;         -- DOUBLE PRECISION（FLOAT 优先级更高!）
-- 这意味着 NUMERIC 的精确性在与 FLOAT 混合运算时会丢失。
-- 最佳实践: 不要混合 NUMERIC 和 FLOAT。

-- ============================================================
-- 7. 横向对比: 数值类型差异
-- ============================================================

-- 1. 整数类型:
--   PostgreSQL: SMALLINT(2), INTEGER(4), BIGINT(8)，无 UNSIGNED
--   MySQL:      TINYINT(1), SMALLINT(2), MEDIUMINT(3), INT(4), BIGINT(8), 有 UNSIGNED
--   Oracle:     NUMBER(p) 是唯一的数值类型（INT 是 NUMBER(38) 的别名）
--   SQL Server: TINYINT(1), SMALLINT(2), INT(4), BIGINT(8)
--
-- 2. 精确小数:
--   PostgreSQL: NUMERIC（任意精度，p ≤ 131072）
--   MySQL:      DECIMAL（p ≤ 65）
--   Oracle:     NUMBER（任意精度）
--   BigQuery:   NUMERIC（p=38, s=9 固定）
--
-- 3. 布尔:
--   PostgreSQL: 真正的 BOOLEAN (TRUE/FALSE)
--   MySQL:      TINYINT(1) 别名
--   Oracle:     SQL 无布尔
--
-- 4. 溢出处理:
--   PostgreSQL: 整数溢出报错（严格）
--   MySQL:      默认报错（sql_mode=STRICT_*），宽松模式截断为最大值
--   C 语言:     无符号整数溢出回绕，有符号 UB

-- ============================================================
-- 8. 对引擎开发者的启示
-- ============================================================

-- (1) 无 UNSIGNED 是简化类型系统的有意选择:
--     UNSIGNED INT 的溢出语义复杂（C 中 UB），
--     且 BIGINT 的范围（9.2×10^18）已覆盖绝大多数场景。
--     新引擎建议: 不支持 UNSIGNED，除非 MySQL 兼容是硬需求。
--
-- (2) NUMERIC 的任意精度实现:
--     PostgreSQL 的 NUMERIC 以 10000 进制存储，每个 digit 是 0-9999。
--     加减法按位进位，乘除法更复杂。
--     性能: NUMERIC 运算比 INT/FLOAT 慢一个数量级。
--
-- (3) 整数溢出应该报错（PostgreSQL 的做法）:
--     静默溢出（截断或回绕）是安全隐患。
--     PostgreSQL 的整数运算使用 __builtin_add_overflow 等检查溢出。

-- ============================================================
-- 9. 版本演进
-- ============================================================
-- PostgreSQL 全版本: SMALLINT, INTEGER, BIGINT, NUMERIC, REAL, DOUBLE PRECISION
-- PostgreSQL 10:    IDENTITY 列（替代 SERIAL）
-- PostgreSQL 13:    GCD(), LCM() 数学函数
-- PostgreSQL 14:    DIV() 整除函数, EXTRACT 返回 NUMERIC
