-- 达梦 (DM): Math Functions
--
-- 参考资料:
--   [1] 达梦数据库 SQL 语言参考手册
--       https://eco.dameng.com/document/dm/zh-cn/sql-dev/

-- 基本数学函数 (兼容 Oracle)
SELECT ABS(-42) FROM DUAL; SELECT CEIL(4.3) FROM DUAL; SELECT FLOOR(4.7) FROM DUAL;
SELECT ROUND(3.14159, 2) FROM DUAL; SELECT TRUNC(3.14159, 2) FROM DUAL;
SELECT MOD(17, 5) FROM DUAL;
SELECT POWER(2, 10) FROM DUAL; SELECT SQRT(144) FROM DUAL;
SELECT EXP(1) FROM DUAL; SELECT LN(EXP(1)) FROM DUAL; SELECT LOG(10, 1000) FROM DUAL;
SELECT SIGN(-42) FROM DUAL;

-- 三角函数
SELECT SIN(0) FROM DUAL; SELECT COS(0) FROM DUAL; SELECT TAN(0) FROM DUAL;
SELECT ASIN(1) FROM DUAL; SELECT ACOS(1) FROM DUAL; SELECT ATAN(1) FROM DUAL;
SELECT ATAN2(1, 1) FROM DUAL;
SELECT SINH(1) FROM DUAL; SELECT COSH(1) FROM DUAL; SELECT TANH(1) FROM DUAL;

-- GREATEST / LEAST
SELECT GREATEST(1, 5, 3) FROM DUAL; SELECT LEAST(1, 5, 3) FROM DUAL;

-- 位运算
SELECT BITAND(5, 3) FROM DUAL;

-- 注意：达梦兼容 Oracle 数学函数语法
-- 注意：LOG(base, x) 底数在前（同 Oracle）
-- 注意：需要 FROM DUAL
-- 限制：无 PI() 函数（使用 ACOS(-1)）
