-- H2 Database: Math Functions
--
-- 参考资料:
--   [1] H2 Database Documentation - Functions
--       https://h2database.com/html/functions.html

SELECT ABS(-42); SELECT CEIL(4.3); SELECT CEILING(4.3); SELECT FLOOR(4.7);
SELECT ROUND(3.14159, 2); SELECT TRUNCATE(3.14159, 2); SELECT TRUNC(3.14159, 2);
SELECT MOD(17, 5); SELECT 17 % 5;
SELECT POWER(2, 10); SELECT SQRT(144);
SELECT EXP(1); SELECT LN(EXP(1)); SELECT LOG(EXP(1)); SELECT LOG(10, 1000); SELECT LOG10(1000);
SELECT SIGN(-42); SELECT PI();
SELECT RAND(); SELECT RAND(42);
SELECT GREATEST(1, 5, 3); SELECT LEAST(1, 5, 3);

-- 三角函数
SELECT SIN(0); SELECT COS(0); SELECT TAN(0);
SELECT ASIN(1); SELECT ACOS(1); SELECT ATAN(1); SELECT ATAN2(1, 1);
SELECT SINH(1); SELECT COSH(1); SELECT TANH(1);
SELECT DEGREES(PI()); SELECT RADIANS(180);
SELECT COT(1);

-- 位运算
SELECT BITAND(5, 3); SELECT BITOR(5, 3); SELECT BITXOR(5, 3); SELECT BITNOT(5);
SELECT LSHIFT(1, 4); SELECT RSHIFT(16, 2);
SELECT BIT_COUNT(7);

-- 注意：H2 数学函数丰富，兼容多种 SQL 方言
-- 注意：支持函数式和运算符式位运算
