-- Apache Hive: Math Functions
--
-- 参考资料:
--   [1] Hive Language Manual - UDF
--       https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF#LanguageManualUDF-MathematicalFunctions

SELECT ABS(-42); SELECT CEIL(4.3); SELECT CEILING(4.3); SELECT FLOOR(4.7);
SELECT ROUND(3.14159, 2); SELECT BROUND(2.5);           -- 银行家舍入
SELECT MOD(17, 5); SELECT 17 % 5;
SELECT POWER(2, 10); SELECT POW(2, 10); SELECT SQRT(144); SELECT CBRT(27);
SELECT EXP(1); SELECT LN(EXP(1)); SELECT LOG(EXP(1));
SELECT LOG2(1024); SELECT LOG10(1000);
SELECT SIGN(-42); SELECT PI();
SELECT RAND(); SELECT RAND(42);

-- 三角函数
SELECT SIN(0); SELECT COS(0); SELECT TAN(0);
SELECT ASIN(1); SELECT ACOS(1); SELECT ATAN(1);
SELECT DEGREES(PI()); SELECT RADIANS(180);

SELECT GREATEST(1, 5, 3); SELECT LEAST(1, 5, 3);

-- 位运算
SELECT 5 & 3; SELECT 5 | 3; SELECT 5 ^ 3; SELECT ~5;
SELECT SHIFTLEFT(1, 4); SELECT SHIFTRIGHT(16, 2);

-- 其他
SELECT FACTORIAL(5);
SELECT CONV(255, 10, 16);
SELECT WIDTH_BUCKET(42, 0, 100, 10);

-- 注意：Hive 数学函数与 Spark SQL 基本一致
-- 注意：BROUND 银行家舍入
-- 注意：位移使用 SHIFTLEFT/SHIFTRIGHT 函数
