-- Apache Impala: Math Functions
--
-- 参考资料:
--   [1] Impala SQL Reference - Math Functions
--       https://impala.apache.org/docs/build/html/topics/impala_math_functions.html

SELECT ABS(-42); SELECT CEIL(4.3); SELECT CEILING(4.3); SELECT FLOOR(4.7);
SELECT ROUND(3.14159, 2); SELECT TRUNCATE(3.14159, 2);
SELECT MOD(17, 5); SELECT 17 % 5; SELECT FMOD(17.5, 5.0);   -- 浮点取模
SELECT POWER(2, 10); SELECT POW(2, 10); SELECT SQRT(144);
SELECT EXP(1); SELECT LN(EXP(1)); SELECT LOG(EXP(1));
SELECT LOG2(1024); SELECT LOG10(1000);
SELECT SIGN(-42); SELECT PI();
SELECT RAND(); SELECT RAND(42);
SELECT GREATEST(1, 5, 3); SELECT LEAST(1, 5, 3);

SELECT SIN(0); SELECT COS(0); SELECT TAN(0);
SELECT ASIN(1); SELECT ACOS(1); SELECT ATAN(1); SELECT ATAN2(1, 1);
SELECT DEGREES(PI()); SELECT RADIANS(180);
SELECT COT(1);
SELECT SINH(1); SELECT COSH(1); SELECT TANH(1);

-- 位运算
SELECT BITAND(5, 3); SELECT BITOR(5, 3); SELECT BITXOR(5, 3); SELECT BITNOT(5);
SELECT SHIFTLEFT(1, 4); SELECT SHIFTRIGHT(16, 2);

-- 注意：Impala 数学函数丰富
-- 注意：FMOD 用于浮点取模
-- 注意：位运算使用函数形式
