-- SAP HANA: Math Functions
--
-- 参考资料:
--   [1] SAP HANA SQL Reference - Numeric Functions
--       https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/

SELECT ABS(-42) FROM DUMMY; SELECT CEIL(4.3) FROM DUMMY; SELECT FLOOR(4.7) FROM DUMMY;
SELECT ROUND(3.14159, 2) FROM DUMMY;
SELECT MOD(17, 5) FROM DUMMY;
SELECT POWER(2, 10) FROM DUMMY; SELECT SQRT(144) FROM DUMMY;
SELECT EXP(1) FROM DUMMY; SELECT LN(EXP(1)) FROM DUMMY;
SELECT LOG(10, 1000) FROM DUMMY;
SELECT SIGN(-42) FROM DUMMY;
SELECT RAND() FROM DUMMY;

SELECT SIN(0) FROM DUMMY; SELECT COS(0) FROM DUMMY; SELECT TAN(0) FROM DUMMY;
SELECT ASIN(1) FROM DUMMY; SELECT ACOS(1) FROM DUMMY; SELECT ATAN(1) FROM DUMMY;
SELECT ATAN2(1, 1) FROM DUMMY;
SELECT SINH(1) FROM DUMMY; SELECT COSH(1) FROM DUMMY; SELECT TANH(1) FROM DUMMY;

SELECT GREATEST(1, 5, 3) FROM DUMMY; SELECT LEAST(1, 5, 3) FROM DUMMY;

SELECT BITAND(5, 3) FROM DUMMY;
-- BITOR, BITXOR, BITNOT 也可用

-- 其他
SELECT HEXTOBIN('FF') FROM DUMMY;
SELECT BINTOHEX(X'FF') FROM DUMMY;
SELECT NDIV0(10, 0) FROM DUMMY;           -- 0 (安全除法)

-- 注意：SAP HANA 需要 FROM DUMMY（类似 Oracle 的 DUAL）
-- 注意：LOG(base, x) 底数在前
-- 注意：NDIV0 安全除法（除以零返回 0）
