-- Apache Spark SQL: Math Functions
--
-- 参考资料:
--   [1] Spark SQL Reference - Math Functions
--       https://spark.apache.org/docs/latest/api/sql/index.html

SELECT ABS(-42); SELECT CEIL(4.3); SELECT CEILING(4.3); SELECT FLOOR(4.7);
SELECT ROUND(3.14159, 2); SELECT BROUND(2.5);           -- 银行家舍入
SELECT MOD(17, 5); SELECT 17 % 5;
SELECT POWER(2, 10); SELECT POW(2, 10); SELECT SQRT(144); SELECT CBRT(27);
SELECT EXP(1); SELECT LN(EXP(1)); SELECT LOG(EXP(1)); SELECT LOG(10, 1000);
SELECT LOG2(1024); SELECT LOG10(1000);
SELECT SIGN(-42); SELECT SIGNUM(-42); SELECT PI();
SELECT RAND(); SELECT RAND(42); SELECT RANDN();          -- RANDN = 正态分布
SELECT E();                               -- 欧拉数

SELECT SIN(0); SELECT COS(0); SELECT TAN(0);
SELECT ASIN(1); SELECT ACOS(1); SELECT ATAN(1); SELECT ATAN2(1, 1);
SELECT DEGREES(PI()); SELECT RADIANS(180);
SELECT SINH(1); SELECT COSH(1); SELECT TANH(1);

SELECT GREATEST(1, 5, 3); SELECT LEAST(1, 5, 3);

SELECT 5 & 3; SELECT 5 | 3; SELECT 5 ^ 3; SELECT ~5;
SELECT SHIFTLEFT(1, 4); SELECT SHIFTRIGHT(16, 2);
SELECT SHIFTRIGHTUNSIGNED(16, 2);         -- 无符号右移
SELECT BIT_COUNT(7);

-- 其他
SELECT FACTORIAL(5); SELECT CONV(255, 10, 16);
SELECT BIN(255); SELECT HEX(255); SELECT UNHEX('FF');
SELECT WIDTH_BUCKET(42, 0, 100, 10);

-- 注意：Spark SQL 数学函数与 Hive 兼容
-- 注意：BROUND 银行家舍入
-- 注意：RANDN() 生成正态分布随机数
