-- Databricks SQL: CREATE TABLE
--
-- 参考资料:
--   [1] Databricks SQL - CREATE TABLE
--       https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-create-table.html
--   [2] Delta Lake Documentation
--       https://docs.delta.io/latest/index.html
--   [3] Databricks - Liquid Clustering
--       https://docs.databricks.com/en/delta/clustering.html

-- ============================================================
-- 1. 基本语法（Delta Lake 格式，默认）
-- ============================================================
CREATE TABLE users (
    id         BIGINT GENERATED ALWAYS AS IDENTITY,
    username   STRING NOT NULL,
    email      STRING NOT NULL,
    age        INT,
    balance    DECIMAL(10, 2) DEFAULT 0.00,
    bio        STRING,
    created_at TIMESTAMP NOT NULL DEFAULT current_timestamp(),
    updated_at TIMESTAMP NOT NULL DEFAULT current_timestamp(),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- ============================================================
-- 2. 语法设计分析（对 SQL 引擎开发者）
-- ============================================================

-- 2.1 Delta Lake: Lakehouse 架构的核心
-- Databricks 所有表默认使用 Delta Lake 格式，这是其最核心的设计选择。
-- Delta Lake 在 Parquet 文件上增加了事务日志（_delta_log/），实现:
--   - ACID 事务: 每次写入是原子的，中途失败不会留下脏数据
--   - Time Travel: 访问任意历史版本（TIMESTAMP AS OF / VERSION AS OF）
--   - Schema Evolution: ALTER TABLE ADD COLUMNS 不需要重写数据
--   - Schema Enforcement: 写入时检查数据是否符合 Schema
--   - MERGE INTO: 高效的 Upsert 操作
--
-- 设计 trade-off:
--   优点: 在数据湖（S3/ADLS/GCS）上获得数据仓库级别的可靠性
--   缺点: 事务日志需要额外存储和维护（VACUUM 清理过期文件）；
--         小文件问题（频繁写入产生大量小 Parquet 文件，需要 OPTIMIZE 合并）
--
-- 对比其他表格式:
--   Iceberg:  Netflix 开源，社区更开放；Trino/Spark/Flink 都有良好支持
--   Hudi:     Uber 开源，侧重增量处理（CDC + Upsert），写入路径更优化
--   Hive:     传统方式（目录分区 + 文件），无 ACID（Hive 3 的 ACID 限制很多）
--
-- 对引擎开发者的启示:
--   Lakehouse 架构的核心创新: 事务日志 + 列存文件 = ACID on 对象存储。
--   如果设计类似系统，关键决策是事务日志的存储方式:
--   Delta Log → JSON/Parquet 文件（Delta Lake）
--   Metadata Tree → Avro/REST Catalog（Iceberg）
--   Timeline → Avro 文件（Hudi）

-- 2.2 GENERATED ALWAYS AS IDENTITY: 分布式自增
-- Databricks 使用 SQL 标准的 IDENTITY 语法（非 AUTO_INCREMENT）。
-- 但在分布式环境下，ID 不保证连续:
--   - Databricks 按批次预分配 ID 段给各 Worker
--   - 批次间可能有间隙（如分配 1-1000, 1001-2000，但实际只用了 500 个）
--   - 不同执行之间也不保证顺序
--
-- 也可以指定起始值和步长:
CREATE TABLE orders_seq (
    id     BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    amount DECIMAL(10,2)
);
-- 或允许手动指定:
CREATE TABLE orders_default (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    amount DECIMAL(10,2)
);
--
-- 对比:
--   MySQL:      AUTO_INCREMENT（保证连续，但重启可能回退 5.7-）
--   PostgreSQL: SERIAL → IDENTITY（10+，保证全局唯一但不保证连续）
--   Flink:      无自增（数据来自外部系统）
--   Trino:      无自增（查询引擎不负责 ID 生成）
--   DuckDB:     SEQUENCE（单机，保证连续）
--   Snowflake:  AUTOINCREMENT（不保证连续，与 Databricks 类似）

-- 2.3 Unity Catalog: 三级命名空间治理
-- catalog.schema.table
CREATE TABLE my_catalog.my_schema.users (
    id       BIGINT GENERATED ALWAYS AS IDENTITY,
    username STRING NOT NULL
);
-- Unity Catalog 提供:
--   - 细粒度权限（列级别 ACL）
--   - 数据血缘（Lineage）自动追踪
--   - 跨工作空间共享数据
--   - 审计日志（谁在什么时候访问了什么数据）
--
-- 对比:
--   Trino:    catalog.schema.table（类似三级，但无统一治理层）
--   Hive:     database.table（两级，MetaStore 作为 Catalog）
--   Snowflake: database.schema.table（三级，与 Databricks 类似）
--   BigQuery: project.dataset.table（三级，GCP 原生治理）

-- ============================================================
-- 3. Liquid Clustering: 取代传统分区的创新
-- ============================================================
-- 传统分区（仍支持，但不推荐新表使用）
CREATE TABLE events_partitioned (
    id         BIGINT GENERATED ALWAYS AS IDENTITY,
    event_type STRING,
    event_date DATE,
    user_id    BIGINT
) PARTITIONED BY (event_date);

-- Liquid Clustering（2023+，推荐）
CREATE TABLE events_v2 (
    id         BIGINT GENERATED ALWAYS AS IDENTITY,
    event_type STRING,
    event_date DATE,
    user_id    BIGINT
) CLUSTER BY (event_date, event_type);

-- 可以随时修改 Clustering Key（传统分区做不到！）
ALTER TABLE events_v2 CLUSTER BY (event_date, user_id);
ALTER TABLE events_v2 CLUSTER BY NONE;  -- 取消 Clustering

-- 设计分析:
--   传统分区的问题: 分区键选定后无法修改，选错代价极大
--   Liquid Clustering 的创新: 增量式重组数据布局，不需要重写全表
--   内部实现: 基于 Hilbert Space-Filling Curve（多维数据排列优化）
--
-- 对比:
--   传统 Hive 分区:   静态目录结构，一旦选定不可修改
--   Iceberg 分区:     Hidden Partitioning（分区对用户透明），但不能修改分区策略
--   Z-ORDER:          Databricks 旧方案，需要手动运行 OPTIMIZE ... ZORDER BY
--   Liquid Clustering: 自动增量维护，支持修改 Key，取代 Z-ORDER + 分区

-- ============================================================
-- 4. CLONE: Delta Lake 特有的表复制
-- ============================================================
-- DEEP CLONE（完整复制数据文件）
CREATE TABLE users_clone DEEP CLONE users;

-- SHALLOW CLONE（共享底层 Parquet 文件，仅复制元数据）
CREATE TABLE users_shallow SHALLOW CLONE users;

-- Time Travel + Clone（从历史版本克隆）
CREATE TABLE users_v5 DEEP CLONE users VERSION AS OF 5;
CREATE TABLE users_snapshot DEEP CLONE users TIMESTAMP AS OF '2024-01-15 10:00:00';

-- 设计分析:
--   SHALLOW CLONE 的关键价值: 零拷贝创建测试/开发环境
--   底层实现: 指向相同的 Parquet 文件（Copy-on-Write 语义）
--   写入 SHALLOW CLONE 后，修改的数据存储在新文件中，原始文件不受影响
--
-- 对比:
--   PostgreSQL: 无 CLONE（需要 pg_dump/pg_restore）
--   MySQL:      无 CLONE（CTAS 不复制索引/约束）
--   Snowflake:  CLONE（零拷贝，与 SHALLOW CLONE 类似）
--   Trino:      CTAS + WITH NO DATA（只能复制结构，无 CLONE 语义）
--   DuckDB:     CTAS（需要完整复制数据）

-- ============================================================
-- 5. 表属性与维护命令
-- ============================================================
CREATE TABLE logs (
    id         BIGINT GENERATED ALWAYS AS IDENTITY,
    message    STRING,
    created_at TIMESTAMP
) TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.logRetentionDuration' = 'interval 30 days',
    'delta.deletedFileRetentionDuration' = 'interval 7 days'
);

-- OPTIMIZE（合并小文件，Delta Lake 必要维护）
OPTIMIZE events;
OPTIMIZE events WHERE event_date >= '2024-01-01';

-- Z-ORDER（传统数据布局优化，Liquid Clustering 出现前的方案）
OPTIMIZE events ZORDER BY (user_id, event_type);

-- VACUUM（清理过期文件，回收存储空间）
VACUUM events;
VACUUM events RETAIN 168 HOURS;  -- 默认 7 天

-- ============================================================
-- 6. 外部表与多格式支持
-- ============================================================
CREATE TABLE external_events (
    id         BIGINT,
    event_type STRING,
    event_date DATE
) USING PARQUET LOCATION 's3://my-bucket/events/';

CREATE TABLE csv_data (col1 STRING, col2 INT)
USING CSV OPTIONS (header 'true', delimiter ',')
LOCATION 's3://my-bucket/csv-data/';

-- CTAS
CREATE OR REPLACE TABLE users_summary AS
SELECT city, COUNT(*) AS cnt, AVG(age) AS avg_age FROM users GROUP BY city;

-- ============================================================
-- 7. 横向对比: Databricks vs 其他引擎
-- ============================================================
-- 1. 存储层:
--   Databricks: Delta Lake（Parquet + 事务日志），ACID，Time Travel
--   Flink:      不存储数据（Connector 映射外部系统）
--   DuckDB:     自有列式存储格式（单文件）
--   Trino:      不存储数据（取决于 Connector: Hive/Iceberg/Delta）

-- 2. 数据维护:
--   Databricks: OPTIMIZE + VACUUM + Liquid Clustering（自动化程度最高）
--   Trino:      依赖底层存储的维护（Iceberg expireSnapshots/rewriteDataFiles）
--   Flink:      无维护概念（流式持续处理）
--   DuckDB:     无维护需求（嵌入式，文件紧凑）

-- 3. Time Travel:
--   Databricks: VERSION AS OF / TIMESTAMP AS OF（Delta Log 驱动）
--   Trino:      Iceberg 支持 FOR VERSION AS OF / FOR TIMESTAMP AS OF
--   DuckDB:     无 Time Travel
--   Flink:      无 Time Travel（流处理面向未来，不回溯）

-- ============================================================
-- 8. 版本演进
-- ============================================================
-- Databricks SQL (2020): 独立 SQL 端点，Photon C++ 引擎
-- Delta Lake 1.0 (2022): 开源版本，MERGE/UPDATE/DELETE
-- Unity Catalog (2022):  统一元数据治理
-- Liquid Clustering (2023): 取代分区 + Z-ORDER
-- Delta Lake 3.0 (2023):   UniForm（一份数据同时支持 Delta/Iceberg/Hudi 读取）
-- Databricks SQL 2024:     Serverless SQL Warehouse 默认，AI Functions
-- Unity Catalog 开源 (2024-06): 开源版本，支持多引擎
-- Delta Lake 4.0 (2025):   Variant 类型、增强的 Liquid Clustering
--
-- 对引擎开发者的参考:
--   Databricks 的 Lakehouse 路径: 先统一存储（Delta Lake）→ 再统一治理（Unity Catalog）
--   → 最后统一计算（Photon + SQL + AI）。
--   关键趋势: 表格式之争（Delta vs Iceberg vs Hudi）走向互通（UniForm）。
